--Item definition for selling stuff, if the item is not here the default price will be Shop.defaultPrice 
-- and broken price will be Shop.defaultPriceBroken

-- If a item has a sell price equal to 0 it won't show up in the ShopUI window
Shop.defaultPriceBroken = 1 -- Default sell price for broken items
Shop.defaultPrice = 0 -- Default sell price for items 
Shop.SellisBlacklist = false -- Use Shop.Sell as blacklist
Shop.SellisWhitelist = true -- Use Shop.Sell as whitelist
-- If Shop.SellisBlacklist and Shop.SellisWhitelist set to false every item is sellable
Shop.Sell = {
	
	[""] = { price = 0, faction = {"Military"} }, -- default case
	["Base.GunPowder"] = { price = 3, faction = {"Military", "Mercs"} },
	["Base.GunToolKit"] = { price = 140, faction = {"Military", "Mercs"} },
	["Base.TinnedBeans"] = { price = 25, faction = {"Military"} },
	["Base.CannedCarrots"] = { price = 25, faction = {"Military"} },
	["Base.CannedChili"] = { price = 25, faction = {"Military"} },
	["Base.CannedCorn"] = { price = 25, faction = {"Military"} },
	["Base.CannedCornedBeef"] = { price = 25, faction = {"Military"} },
	["Base.CannedFruitCocktail"] = { price = 25, faction = {"Military"} },
	["Base.CannedMushroomSoup"] = { price = 25, faction = {"Military"} },
	["Base.CannedPeas"] = { price = 25, faction = {"Military"} },
	["Base.CannedPeaches"] = { price = 25, faction = {"Military"} },
	["Base.CannedPineapple"] = { price = 25, faction = {"Military"} },
	["Base.CannedPotato2"] = { price = 25, faction = {"Military"} },
	["Base.CannedSardines"] = { price = 25, faction = {"Military"} },
	["Base.TinnedSoup"] = { price = 25, faction = {"Military"} },
	["Base.CannedBolognese"] = { price = 25, faction = {"Military"} },
	["Base.CannedMilk"] = { price = 25, faction = {"Military"} },
	["Base.CannedTomato2"] = { price = 25, faction = {"Military"} },
	["Base.CannedCarrots2"] = { price = 25, faction = {"Military"} },
	["Base.TunaTin"] = { price = 25, faction = {"Military"} },
	["Base.Makarov"] = { price = 300, faction = {"Military"} },
	["Base.Dogfood"] = { price = 25, faction = {"Military"} },
	["Greenfire.Tobacco"] = { price = 3, faction = {"Military"} },
	["Base.WristWatch_Right_ClassicBlack"] = { price = 20, faction = {"Military", "Duty"} },
	["Base.WristWatch_Left_ClassicBlack"] = { price = 20, faction = {"Military", "Duty"} },
	["Base.WristWatch_Right_ClassicBrown"] = { price = 20, faction = {"Military", "Duty"} },
	["Base.WristWatch_Left_ClassicBrown"] = { price = 20, faction = {"Military", "Duty"} },
	["Base.WristWatch_Right_ClassicMilitary"] = { price = 100, faction = {"Military", "Duty"} },
	["Base.WristWatch_Left_ClassicMilitary"] = { price = 100, faction = {"Military", "Duty"} },
	["Base.WristWatch_Right_ClassicGold"] = { price = 50, faction = {"Military", "Duty"} },
	["Base.WristWatch_Left_ClassicGold"] = { price = 50, faction = {"Military", "Duty"} },
	["Base.WristWatch_Right_DigitalBlack"] = { price = 30, faction = {"Military", "Duty"} },
	["Base.WristWatch_Left_DigitalBlack"] = { price = 30, faction = {"Military", "Duty"} },
	["Base.WristWatch_Right_DigitalRed"] = { price = 30, faction = {"Military", "Duty"} },
	["Base.WristWatch_Left_DigitalRed"] = { price = 30, faction = {"Military", "Duty"} },
	["Base.WristWatch_Right_DigitalDress"] = { price = 50, faction = {"Military", "Duty"} },
	["Base.WristWatch_Left_DigitalDress"] = { price = 50, faction = {"Military", "Duty"} },

	--BANDITS/FREEDOM
	["Base.Baker_Tent_6"] = { price = 250, faction = {"Bandits", "Freedom"} },
	["Base.Baker_Tent_5"] = { price = 250, faction = {"Bandits", "Freedom"} },
	["Base.Baker_Tent_4"] = { price = 250, faction = {"Bandits", "Freedom"} },
	["Base.Baker_Tent_3"] = { price = 250, faction = {"Bandits", "Freedom"} },
	["Base.Baker_Tent_2"] = { price = 250, faction = {"Bandits", "Freedom"} },
	["Base.Baker_Tent_1"] = { price = 250, faction = {"Bandits", "Freedom"} },
	["Base.Bass"] = { price = 30, faction = {"Military", "Freedom"} },
	["Base.Catfish"] = { price = 69, faction = {"Military", "Freedom"} },
	["Base.Crappie"] = { price = 30, faction = {"Military", "Freedom"} },
	["Base.Perch"] = { price = 30, faction = {"Military", "Freedom"} },
	["Base.Pike"] = { price = 90, faction = {"Military", "Freedom"} },
	["Base.Panfish"] = { price = 30, faction = {"Military", "Freedom"} },
	["Base.Trout"] = { price = 120, faction = {"Military", "Freedom"} },
	["Base.DeadBird"] = { price = 30, faction = {"Bandits", "Freedom"} },
	["Base.DeadMouse"] = { price = 30, faction = {"Bandits", "Freedom"} },
	["Base.DeadRabbit"] = { price = 90, faction = {"Bandits", "Freedom"} },
	["Base.DeadRat"] = { price = 30, faction = {"Bandits", "Freedom"} },
	["Base.DeadSquirrel"] = { price = 120, faction = {"Bandits", "Freedom"} },
	["Greenfire.GFGrinder"] = { price = 300, faction = {"Bandits", "Freedom"} },
	["Base.GuitarElectricBlack"] = { price = 200, faction = {"Bandits", "Freedom"} },
	["Base.GuitarElectricBlue"] = { price = 90, faction = {"Bandits", "Freedom"} },
	["Base.GuitarElectricRed"] = { price = 150, faction = {"Bandits", "Freedom"} },
	["Base.Trumpet"] = { price = 120, faction = {"Bandits", "Freedom"} },
	["Base.GuitarAcoustic"] = { price = 120, faction = {"Bandits"} },
	["Base.GuitarAcoustic"] = { price = 420, faction = {"Freedom"} },


	-- Mercs
	["Base.Bullets357"] = { price = 4, faction = {"Mercs"} },
	["Base.Bullets22"] = { price = 4, faction = {"Mercs"} },
	["Base.Bullets4440"] = { price = 4, faction = {"Mercs"} },
	["Base.Bullets4440"] = { price = 4, faction = {"Mercs"} },
	["Base.9mmCompensator"] = { price = 190, faction = {"Mercs"} },
	["Base.9mmSilencer"] = { price = 190, faction = {"Mercs"} },
	["Base.ShotgunSilencer"] = { price = 100, faction = {"Mercs"} },
	["Base.Laser"] = { price = 150, faction = {"Mercs"} },
	["Base.x2LeupoldScope"] = { price = 185, faction = {"Mercs"} },
	["Base.HeadhunterScope"] = { price = 240, faction = {"Mercs"} },
	["Base.x4-x12Scope"] = { price = 240, faction = {"Mercs"} },
	["Base.x8Scope"] = { price = 240, faction = {"Mercs"} },
	["Base.45Silencer"] = { price = 190, faction = {"Mercs"} },
	["Base.38Silencer"] = { price = 220, faction = {"Mercs"} },
	["Base.308Silencer"] = { price = 300, faction = {"Mercs"} },
	["Base.223Silencer"] = { price = 190, faction = {"Mercs"} },
	["Base.22Silencer"] = { price = 190, faction = {"Mercs"} },
	["Base.Hat_SpoonSkullMask"] = { price = 300, faction = {"Mercs"} },
	["Base.SpoonSkull"] = { price = 200, faction = {"Mercs"} },
	["Base.TvAntique"] = { price = 350, faction = {"Mercs"} },
	["Base.Mov_AntiqueStove"] = { price = 750, faction = {"Mercs"} },
	["Base.Shotgun"] = { price = 150, faction = {"Mercs"} },
	["Base.Mossberg500"] = { price = 200, faction = {"Mercs"} },
	["Base.Mossberg500Tactical"] = { price = 250, faction = {"Mercs"} },
	["Base.ShotgunSawnoff"] = { price = 150, faction = {"Mercs"} },
	["Base.EmptyJar"] = { price = 600, faction = {"Mercs"} },
	["Base.JarLid"] = { price = 600, faction = {"Mercs"} },
	["Base.Thread"] = { price = 30, faction = {"Mercs"} },	
	["UndeadSurvivor.BountyPhoto01"] = { price = 600, faction = {"Mercs"} },
	["UndeadSurvivor.BountyPhoto02"] = { price = 600, faction = {"Mercs"} },
	["UndeadSurvivor.BountyPhoto03"] = { price = 600, faction = {"Mercs"} },
	["UndeadSurvivor.BountyPhoto04"] = { price = 600, faction = {"Mercs"} },
	["UndeadSurvivor.BountyPhoto05"] = { price = 600, faction = {"Mercs"} },
	["UndeadSurvivor.BountyPhoto06"] = { price = 600, faction = {"Mercs"} },
	["UndeadSurvivor.BountyPhoto07"] = { price = 600, faction = {"Mercs"} },
	["UndeadSurvivor.BountyPhoto08"] = { price = 600, faction = {"Mercs"} },
	["UndeadSurvivor.BountyPhoto09"] = { price = 600, faction = {"Mercs"} },
	["UndeadSurvivor.BountyPhoto10"] = { price = 600, faction = {"Mercs"} },

	
	-- bounty photo
	
		
	--BANDITS
	
	["Base.PillsSleepingTablets"] = { price = 95, faction = {"Bandits"} },
	["Base.Wine"] = { price = 65, faction = {"Bandits"} },
	["Base.Wine2"] = { price = 65, faction = {"Bandits"} },
	["Base.BeerCan"] = { price = 50, faction = {"Bandits"} },
	["MethCooking.MethGood"] = { price = 25, faction = {"Bandits"} },
	["MethCooking.MethBad"] = { price = 5, faction = {"Bandits"} },
	["DrugMod.Meth"] = { price = 90, faction = {"Bandits", "Duty"} },
	["DrugMod.LowQualityMeth"] = { price = 40, faction = {"Bandits", "Duty"} },
	["DrugMod.MediocreMeth"] = { price = 60, faction = {"Bandits", "Duty"} },
	["DrugMod.Cocaine"] = { price = 45, faction = {"Bandits", "Duty"} },
	["DrugMod.Crack"] = { price = 90, faction = {"Bandits", "Duty"} },
	["Base.Necklace_DogTag"] = { price = 10, faction = {"Bandits", "Duty"} },
	["Base.Necklace_Gold"] = { price = 20, faction = {"Bandits", "Duty"} },
	["Base.Necklace_GoldRuby"] = { price = 20, faction = {"Bandits", "Duty"} },
	["Base.Necklace_GoldDiamond"] = { price = 20, faction = {"Bandits", "Duty"} },
	["Base.Necklace_Silver"] = { price = 3, faction = {"Bandits", "Duty"} },
	["Base.Necklace_SilverSapphire"] = { price = 3, faction = {"Bandits", "Duty"} },
	["Base.Necklace_SilverCrucifix"] = { price = 3, faction = {"Bandits", "Duty"} },
	["Base.Necklace_SilverDiamond"] = { price = 3, faction = {"Bandits", "Duty"} },
	["Base.Necklace_Crucifix"] = { price = 3, faction = {"Bandits", "Duty"} },
	["Base.Necklace_YingYang"] = { price = 3, faction = {"Bandits", "Duty"} },
	["Base.Necklace_Pearl"] = { price = 3, faction = {"Bandits", "Duty"} },
	["Base.NecklaceLong_Gold"] = { price = 20, faction = {"Bandits", "Duty"} },
	["Base.NecklaceLong_GoldDiamond"] = { price = 20, faction = {"Bandits", "Duty"} },
	["Base.NecklaceLong_Silver"] = { price = 3, faction = {"Bandits", "Duty"} },
	["Base.NecklaceLong_SilverEmerald"] = { price = 5, faction = {"Bandits", "Duty"} },
	["Base.NecklaceLong_SilverSapphire"] = { price = 5, faction = {"Bandits", "Duty"} },
	["Base.NecklaceLong_SilverDiamond"] = { price = 5, faction = {"Bandits", "Duty"} },
	["Base.NecklaceLong_Amber"] = { price = 3, faction = {"Bandits", "Duty"} },
	["Base.Necklace_Choker"] = { price = 3, faction = {"Bandits", "Duty"} },
	["Base.Necklace_Choker_Sapphire"] = { price = 3, faction = {"Bandits", "Duty"} },
	["Base.Necklace_Choker_Amber"] = { price = 3, faction = {"Bandits", "Duty"} },
	["Base.Necklace_Choker_Diamond"] = { price = 3, faction = {"Bandits", "Duty"} },
	["Base.Locket"] = { price = 3, faction = {"Bandits", "Duty"} },
	["Base.NoseRing_Gold"] = { price = 20, faction = {"Bandits", "Duty"} },
	["Base.NoseRing_Silver"] = { price = 1, faction = {"Bandits", "Duty"} },	
	["Base.NoseStud_Gold"] = { price = 20, faction = {"Bandits", "Duty"} },
	["Base.NoseStud_Silver"] = { price = 1, faction = {"Bandits", "Duty"} },	
	["Base.Earring_LoopLrg_Gold"] = { price = 20, faction = {"Bandits", "Duty"} },
	["Base.Earring_LoopLrg_Silver"] = { price = 1, faction = {"Bandits", "Duty"} },
	["Base.Earring_LoopMed_Silver"] = { price = 1, faction = {"Bandits", "Duty"} },
	["Base.Earring_LoopMed_Gold"] = { price = 20, faction = {"Bandits", "Duty"} },
	["Base.Earring_LoopSmall_Silver_Both"] = { price = 1, faction = {"Bandits", "Duty"} },	
	["Base.Earring_LoopSmall_Gold_Both"] = { price = 20, faction = {"Bandits", "Duty"} },	
	["Base.Earring_LoopSmall_Silver_Top"] = { price = 1, faction = {"Bandits", "Duty"} },	
	["Base.Earring_LoopSmall_Gold_Top"] = { price = 20, faction = {"Bandits", "Duty"} },	
	["Base.Earring_Stud_Gold"] = { price = 20, faction = {"Bandits", "Duty"} },
	["Base.Earring_Stud_Silver"] = { price = 1, faction = {"Bandits", "Duty"} },
	["Base.Earring_Stone_Sapphire"] = { price = 2, faction = {"Bandits", "Duty"} },
	["Base.Earring_Stone_Emerald"] = { price = 2, faction = {"Bandits", "Duty"} },
	["Base.Earring_Stone_Ruby"] = { price = 2, faction = {"Bandits", "Duty"} },
	["Base.Earring_Pearl"] = { price = 1, faction = {"Bandits", "Duty"} },	
	["Base.Earring_Dangly_Sapphire"] = { price = 2, faction = {"Bandits", "Duty"} },	
	["Base.Earring_Dangly_Emerald"] = { price = 2, faction = {"Bandits", "Duty"} },
	["Base.Earring_Dangly_Ruby"] = { price = 2, faction = {"Bandits", "Duty"} },	
	["Base.Earring_Dangly_Diamond"] = { price = 2, faction = {"Bandits", "Duty"} },
	["Base.Earring_Dangly_Pearl"] = { price = 2, faction = {"Bandits", "Duty"} },	
	["Base.Ring_Right_MiddleFinger_Gold"] = { price = 20, faction = {"Bandits", "Duty"} },	 
	["Base.Ring_Left_MiddleFinger_Gold"] = { price = 20, faction = {"Bandits", "Duty"} },	
	["Base.Ring_Right_RingFinger_Gold"] = { price = 20, faction = {"Bandits", "Duty"} },	
	["Base.Ring_Left_RingFinger_Gold"] = { price = 20, faction = {"Bandits", "Duty"} },
	["Base.Ring_Right_MiddleFinger_GoldDiamond"] = { price = 20, faction = {"Bandits", "Duty"} },
	["Base.Ring_Left_MiddleFinger_GoldDiamond"] = { price = 20, faction = {"Bandits", "Duty"} },	
	["Base.Ring_Right_RingFinger_GoldDiamond"] = { price = 20, faction = {"Bandits", "Duty"} },
	["Base.Ring_Left_RingFinger_GoldDiamond"] = { price = 20, faction = {"Bandits", "Duty"} },
	["Base.Ring_Right_MiddleFinger_GoldRuby"] = { price = 20, faction = {"Bandits", "Duty"} },
	["Base.Ring_Left_MiddleFinger_GoldRuby"] = { price = 20, faction = {"Bandits", "Duty"} },	
	["Base.Ring_Right_RingFinger_GoldRuby"] = { price = 20, faction = {"Bandits", "Duty"} },	
	["Base.Ring_Left_RingFinger_GoldRuby"] = { price = 20, faction = {"Bandits", "Duty"} },
	["Base.Ring_Right_MiddleFinger_Silver"] = { price = 1, faction = {"Bandits", "Duty"} },
	["Base.Ring_Left_MiddleFinger_Silver"] = { price = 1, faction = {"Bandits", "Duty"} },
	["Base.Ring_Right_RingFinger_Silver"] = { price = 1, faction = {"Bandits", "Duty"} },	
	["Base.Ring_Left_RingFinger_Silver"] = { price = 1, faction = {"Bandits", "Duty"} },	
	["Base.Ring_Right_MiddleFinger_SilverDiamond"] = { price = 2, faction = {"Bandits", "Duty"} },	
	["Base.Ring_Left_MiddleFinger_SilverDiamond"] = { price = 2, faction = {"Bandits", "Duty"} },	
	["Base.Ring_Right_RingFinger_SilverDiamond"] = { price = 2, faction = {"Bandits", "Duty"} },
	["Base.Ring_Left_RingFinger_SilverDiamond"] = { price = 2, faction = {"Bandits", "Duty"} },
	["Base.WeddingRing_Man"] = { price = 1, faction = {"Bandits", "Duty"} },
	["Base.WeddingRing_Woman"] = { price = 1, faction = {"Bandits", "Duty"} },
	["iMeds.SyringeWithNeedle"] = { price = 70, faction = {"Bandits", "Duty"} },
	["iMeds.SyringePack"] = { price = 700, faction = {"Bandits"} },
	["iMeds.UnknownPack"] = { price = 750, faction = {"Bandits"} },
	["Base.WristWatch_Right_ClassicGold"] = { price = 20, faction = {"Military", "Bandits"} },	
	["Base.WristWatch_Left_ClassicGold"] = { price = 20, faction = {"Military", "Bandits"} },	
	["Base.Bracelet_BangleRightGold"] = { price = 3, faction = {"Duty", "Bandits"} },		
	["Base.Bracelet_BangleLeftGold"] = { price = 3, faction = {"Duty", "Bandits"} },	
	["Base.Bracelet_ChainRightGold"] = { price = 20, faction = {"Duty", "Bandits"} },	
	["Base.Bracelet_ChainLeftGold"] = { price = 20, faction = {"Duty", "Bandits"} },	
	["Base.Bracelet_BangleRightSilver"] = { price = 3, faction = {"Duty", "Bandits"} },
	["Base.Bracelet_BangleLeftSilver"] = { price = 3, faction = {"Duty", "Bandits"} },
	["Base.Bracelet_ChainRightSilver"] = { price = 3, faction = {"Duty", "Bandits"} },	
	["Base.Bracelet_ChainLeftSilver"] = { price = 3, faction = {"Duty", "Bandits"} },
	["Base.BellyButton_DangleGold"] = { price = 20, faction = {"Duty", "Bandits"} },	
	["Base.BellyButton_DangleGoldRuby"] = { price = 20, faction = {"Duty", "Bandits"} },	
	["Base.BellyButton_DangleSilver"] = { price = 1, faction = {"Duty", "Bandits"} },	
	["Base.BellyButton_DangleSilverDiamond"] = { price = 1, faction = {"Duty", "Bandits"} },	
	["Base.BellyButton_RingGold"] = { price = 20, faction = {"Duty", "Bandits"} },
	["Base.BellyButton_RingGoldDiamond"] = { price = 2, faction = {"Duty", "Bandits"} },	
	["Base.BellyButton_RingGoldRuby"] = { price = 2, faction = {"Duty", "Bandits"} },	
	["Base.BellyButton_RingSilver"] = { price = 1, faction = {"Duty", "Bandits"} },
	["Base.BellyButton_RingSilverAmethyst"] = { price = 2, faction = {"Duty", "Bandits"} },
	["Base.BellyButton_RingSilverDiamond"] = { price = 2, faction = {"Duty", "Bandits"} },
	["Base.BellyButton_RingSilverRuby"] = { price = 2, faction = {"Duty", "Bandits"} },
	["Base.BellyButton_StudGold"] = { price = 20, faction = {"Duty", "Bandits"} },	
	["Base.BellyButton_StudGoldDiamond"] = { price = 20, faction = {"Duty", "Bandits"} },	
	["Base.BellyButton_StudSilver"] = { price = 2, faction = {"Duty", "Bandits"} },
	["Base.BellyButton_StudSilverDiamond"] = { price = 2, faction = {"Duty", "Bandits"} },	
	["Base.BeerBottle"] = { price = 30, faction = {"Bandits"} },	
	["Base.BeerCan"] = { price = 30, faction = {"Bandits"} },	
	["Greenfire.FreshUnCanna"] = { price = 9, faction = {"Bandits"} },	
	["Base.PillsSleepingTablets"] = { price = 30, faction = {"Bandits"} },	
	["ZBR.TripleSec"] = { price = 30, faction = {"Bandits"} },	
	["iMeds.Morphine"] = { price = 75, faction = {"Bandits"} },
	["iMeds.MorphinePack"] = { price = 750, faction = {"Bandits"} },
	["Base.WhiskeyFull"] = { price = 100, faction = {"Bandits", "Military"} },
	["iMeds.Needle"] = { price = 45, faction = {"Bandits"} },
	["Base.PokerChips"] = { price = 1, faction = {"Bandits"} },

	--ECO
	["iMeds.UmifenovirPack"] = { price = 600, faction = {"Ecologist"} },
	["iMeds.Umifenovir"] = { price = 60, faction = {"Ecologist"} },
	["iMeds.NasivionPack"] = { price = 400, faction = {"Ecologist"} },
	["iMeds.Nasivion"] = { price = 40, faction = {"Ecologist"} },
	["iMeds.NaloxonPack"] = { price = 250, faction = {"Ecologist"} },
	["iMeds.Naloxon"] = { price = 25, faction = {"Ecologist"} },
	["iMeds.HemoStopPack"] = { price = 150, faction = {"Ecologist"} },
	["iMeds.HemoStop"] = { price = 15, faction = {"Ecologist"} },
	["iMeds.ErythropoietinPack"] = { price = 600, faction = {"Ecologist"} },
	["iMeds.Erythropoietin"] = { price = 60, faction = {"Ecologist"} },
	["iMeds.ButamiratePack"] = { price = 300, faction = {"Ecologist"} },
	["iMeds.Butamirate"] = { price = 30, faction = {"Ecologist"} },
	["iMeds.BismuthSubsalicylate"] = { price = 35, faction = {"Ecologist"} },
	["iMeds.Alkagin"] = { price = 200, faction = {"Ecologist"} },
	["iMeds.Alkagin"] = { price = 20, faction = {"Ecologist"} },
	["LabItems.CmpFlaskWithLeukocytes"] = { price = 100, faction = {"Ecologist"} },
	["LabItems.CmpFlaskWithAmmoniumSulfate"] = { price = 100, faction = {"Ecologist"} },
	["iMeds.PlasmaBagON"] = { price = 250, faction = {"Ecologist"} },
	["LabItems.MatTaintedBlood"] = { price = 40, faction = {"Ecologist"} },
	["LabItems.MatInfectedBlood"] = { price = 150, faction = {"Ecologist"} },
	["LabItems.LabSyringe"] = { price = 120, faction = {"Ecologist"} },
	["Base.CarBattery1"] = { price = 9, faction = {"Ecologist"} },
	["Base.CarBattery2"] = { price = 100, faction = {"Ecologist"} },
	["Base.CarBattery3"] = { price = 120, faction = {"Ecologist"} },
	["Base.DuctTape"] = { price = 90, faction = {"Ecologist"} },
	["Base.Battery"] = { price = 70, faction = {"Ecologist"} },
	["Base.Flashlight"] = { price = 100, faction = {"Ecologist"} },
	["Base.ElectronicsScrap"] = { price = 15, faction = {"Ecologist", "Duty"} },
	["Base.Sheet"] = { price = 10, faction = {"Ecologist"} },
	["Base.CampingTentKit"] = { price = 600, faction = {"Ecologist"} },
	["Base.SheetMetal"] = { price = 200, faction = {"Ecologist"} },
	["iMeds.Stethoscope"] = { price = 250, faction = {"Ecologist"} },
	["DrHyde.CureNotes"] = { price = 1500, faction = {"Ecologist"} },
	--BANDITS--MILITARY
	["ZBR.Martini"] = { price = 100, faction = {"Bandits", "Military"} },
	["ZBR.LIIT"] = { price = 120, faction = {"Bandits", "Military"} },
	["ZBR.KYCoffee"] = { price = 95, faction = {"Bandits", "Military"} },
	["ZBR.InsaneBloodyMary"] = { price = 150, faction = {"Bandits", "Military"} },
	["ZBR.ImprovedBloodyMary"] = { price = 120, faction = {"Bandits", "Military"} },
	["ZBR.Highball"] = { price = 40, faction = {"Bandits", "Military"} },
	["ZBR.Gin"] = { price = 90, faction = {"Bandits", "Military"} },
	["ZBR.Flip"] = { price = 110, faction = {"Bandits", "Military"} },
	["ZBR.Rum"] = { price = 80, faction = {"Bandits", "Military"} },
	["ZBR.Daiquiri"] = { price = 24, faction = {"Bandits", "Military"} },
	["ZBR.Cocktail"] = { price = 75, faction = {"Bandits", "Military"} },
	["ZBR.Brandy"] = { price = 42, faction = {"Bandits", "Military"} },
	["ZBR.BloodyMary"] = { price = 110, faction = {"Bandits", "Military"} },
	["ZBR.Bitters"] = { price = 55, faction = {"Bandits", "Military"} },
	["ZBR.Moonshine"] = { price = 200, faction = {"Bandits", "Military"} },
	["ZBR.Sidecar"] = { price = 95, faction = {"Bandits", "Military"} },
	["ZBR.Seltzer"] = { price = 55, faction = {"Bandits", "Military"} },
	["ZBR.Tequila"] = { price = 140, faction = {"Bandits", "Military"} },
	["stalkerfood.CossacksVodka"] = { price = 200, faction = {"Bandits", "Military"} },
	["Base.Cigarettes"] = { price = 30, faction = {"Bandits", "Military"} },
	["stalker.ArtifactWrenched"] = { price = 120, faction = {"Ecologist", "Freedom", "Duty"} },
	["stalker.ArtifactUrchin"] = { price = 54, faction = {"Ecologist", "Freedom", "Duty"} },
	["stalker.ArtifactSun"] = { price = 540, faction = {"Ecologist", "Freedom", "Duty"} },
	["stalker.ArtifactStoneFlower"] = { price = 20, faction = {"Ecologist", "Freedom", "Duty"} },
	["stalker.ArtifactSourpuss"] = { price = 90, faction = {"Ecologist", "Freedom", "Duty"} },
	["stalker.ArtifactSoul"] = { price = 150, faction = {"Ecologist", "Freedom", "Duty"} },
	["stalker.ArtifactSnowflake"] = { price = 220, faction = {"Ecologist", "Freedom", "Duty"} },
	["stalker.ArtifactSignet"] = { price = 184, faction = {"Ecologist", "Freedom", "Duty"} },
	["stalker.ArtifactSeraphim"] = { price = 150, faction = {"Ecologist", "Freedom", "Duty"} },
	["stalker.ArtifactPhantomStar"] = { price = 270, faction = {"Ecologist", "Freedom", "Duty"} },
	["stalker.ArtifactPellicle"] = { price = 330, faction = {"Ecologist", "Freedom", "Duty"} },
	["stalker.ArtifactMamasBeads"] = { price = 1000, faction = {"Ecologist", "Freedom", "Duty"} },
	["stalker.ArtifactHeart"] = { price = 650, faction = {"Ecologist", "Freedom", "Duty"} },
	["stalker.ArtifactFountain"] = { price = 450, faction = {"Ecologist", "Freedom", "Duty"} },
	["stalker.ArtifactFirefly"] = { price = 167, faction = {"Ecologist", "Freedom", "Duty"} },
	["stalker.ArtifactEye"] = { price = 200, faction = {"Ecologist", "Freedom", "Duty"} },
	["stalker.ArtifactCrystalThorn"] = { price = 1500, faction = {"Ecologist", "Freedom", "Duty"} },
	["stalker.ArtifactCrystal"] = { price = 2500, faction = {"Ecologist", "Freedom", "Duty"} },
	["stalker.ArtifactChain"] = { price = 205, faction = {"Ecologist", "Freedom", "Duty"} },
	["stalker.ArtifactCell"] = { price = 105, faction = {"Ecologist", "Freedom", "Duty"} },
	--FREEDOM/DUTY/MIL
	["Base.ScrapMetal"] = { price = 20, faction = {"Military", "Ecologist", "Duty", "Freedom"} },
	["Base.SmallSheetMetal"] = { price = 70, faction = {"Military", "Ecologist", "Duty", "Freedom"} },
	["Base.MetalBar"] = { price = 90, faction = {"Military", "Ecologist", "Duty", "Freedom"} },
	["Base.MetalPipe"] = { price = 100, faction = {"Military", "Ecologist", "Duty", "Freedom"} },
	["Base.SandBag"] = { price = 40, faction = {"Military", "Ecologist", "Duty", "Freedom"} },
	["Base.GravelBag"] = { price = 50, faction = {"Military", "Ecologist", "Duty", "Freedom"} },
	["Base.Solvent"] = { price = 150, faction = {"Military", "Freedom", "Duty"} },
	["Greenfire.Cannabis"] = { price = 9, faction = {"Military", "Freedom", "Duty"} },
	["Greenfire.Joint"] = { price = 14, faction = {"Military", "Freedom", "Duty"} },
	["Greenfire.KiefJoint"] = { price = 33, faction = {"Military", "Freedom", "Duty"} },
	["Greenfire.DryBTobacco"] = { price = 1, faction = {"Military", "Duty",} },

	--ALLfaction
	["Base.PetrolCan"] = { price = 180, faction = {"Military", "Freedom", "Duty", "Ecologist", "Bandits", "Mercs"} },
	["Base.Log"] = { price = 9, faction = {"Military", "Freedom", "Duty", "Ecologist", "Bandits", "Mercs"} },
	["Base.Plank"] = { price = 12, faction = {"Military", "Freedom", "Duty", "Ecologist", "Bandits", "Mercs"} },
	["Base.Garbagebag"] = { price = 50, faction = {"Military", "Freedom", "Duty", "Ecologist", "Bandits", "Mercs"} },
	["Base.RippedSheets"] = { price = 1, faction = {"Military", "Freedom", "Duty", "Ecologist", "Bandits", "Mercs"} },
	["Base.KitchenKnife"] = { price = 50, faction = {"Military", "Freedom", "Duty", "Ecologist", "Bandits", "Mercs"} },
	["Base.Cigarettes"] = { price = 5, faction = {"Military", "Freedom", "Duty", "Ecologist", "Bandits", "Mercs"} },
	["Base.PLGR"] = { price = 350, faction = {"Military", "Freedom", "Duty", "Ecologist", "Bandits", "Mercs"} },
	["Base.Cigarette"] = { price = 5, faction = {"Military", "Freedom", "Duty", "Ecologist", "Bandits", "Mercs"} },
	["CanteensAndBottles.JumboJerryCanTank"] = { price = 290, faction = {"Military", "Freedom", "Duty", "Ecologist", "Bandits", "Mercs"} },
	["Base.HottieZ"] = { price = 5, faction = {"Military", "Freedom", "Duty", "Ecologist", "Bandits", "Mercs"} }

	}

