--Item definition for selling stuff, if the item is not here the default price will be Shop.defaultPrice 
-- and broken price will be Shop.defaultPriceBroken

-- If a item has a sell price equal to 0 it won't show up in the ShopUI window
Shop.defaultPriceBroken = 1 -- Default sell price for broken items
Shop.defaultPrice = 0 -- Default sell price for items 
Shop.SellisBlacklist = false -- Use Shop.Sell as blacklist
Shop.SellisWhitelist = true -- Use Shop.Sell as whitelist
-- If Shop.SellisBlacklist and Shop.SellisWhitelist set to false every item is sellable
Shop.Sell = {
	["Base.Necklace_DogTag"] = { {price = 10, faction = {"Loner"}}, {price = 20, faction = {"Duty"}}, {price = 30, faction = {"Military"}} },
	["Base.GunPowder"] = { {price = 1, faction = {"Loner"}}, {price = 2, faction = {"Duty"}}, {price = 3, faction = {"Military"}} },
	["Base.GunToolKit"] = { {price = 60, faction = {"Loner"}}, {price = 120, faction = {"Duty"}}, {price = 140, faction = {"Military"}} },
	["Base.TinnedBeans"] = { {price = 25, faction = {"Military"}} },
	["Base.CannedCarrots"] = { {price = 25, faction = {"Military"}} },
	["Base.CannedChili"] = { {price = 25, faction = {"Military"}} },
	["Base.CannedCorn"] = { {price = 25, faction = {"Military"}} },
	["Base.CannedCornedBeef"] = { {price = 25, faction = {"Military"}} },
	["Base.CannedFruitCocktail"] = { {price = 25, faction = {"Military"}} },
	["Base.CannedMushroomSoup"] = { {price = 25, faction = {"Military"}} },
	["Base.CannedPeas"] = { {price = 25, faction = {"Military"}} },
	["Base.CannedPeaches"] = { {price = 25, faction = {"Military"}} },
	["Base.CannedPineapple"] = { {price = 25, faction = {"Military"}} },
	["Base.CannedPotato2"] = { {price = 25, faction = {"Military"}} },
	["Base.CannedSardines"] = { {price = 25, faction = {"Military"}} },
	["Base.TinnedSoup"] = { {price = 25, faction = {"Military"}} },
	["Base.CannedBolognese"] = { {price = 25, faction = {"Military"}} },
	["Base.CannedMilk"] = { {price = 25, faction = {"Military"}} },
	["Base.CannedTomato2"] = { {price = 25, faction = {"Military"}} },
	["Base.CannedCarrots2"] = { {price = 25, faction = {"Military"}} },
	["Base.TunaTin"] = { {price = 25, faction = {"Military"}} },
	["Base.Makarov"] = { {price = 300, faction = {"Military"}} },
	["Base.Dogfood"] = { {price = 25, faction = {"Military"}} },
	["Greenfire.Tobacco"] = { {price = 5, faction = {"Military"}}, {price = 4, faction = {"Duty"}}, {price = 3, faction = {"Mercs"}} },
	["Base.WristWatch_Right_ClassicBlack"] = { {price = 10, faction = {"Loner"}}, {price = 20, faction = {"Duty"}}, {price = 30, faction = {"Military"}} },
	["Base.WristWatch_Left_ClassicBlack"] = { {price = 10, faction = {"Loner"}}, {price = 20, faction = {"Duty"}}, {price = 30, faction = {"Military"}} },
	["Base.WristWatch_Right_ClassicBrown"] = { {price = 12, faction = {"Loner"}}, {price = 20, faction = {"Duty"}}, {price = 30, faction = {"Military"}} },
	["Base.WristWatch_Left_ClassicBrown"] = { {price = 15, faction = {"Loner"}}, {price = 20, faction = {"Duty"}}, {price = 30, faction = {"Military"}} },
	["Base.WristWatch_Right_ClassicMilitary"] = { {price = 15, faction = {"Loner"}}, {price = 100, faction = {"Duty"}}, {price = 30, faction = {"Military"}} },
	["Base.WristWatch_Left_ClassicMilitary"] = { {price = 10, faction = {"Loner"}}, {price = 100, faction = {"Duty"}}, {price = 30, faction = {"Military"}} },
	["Base.WristWatch_Right_ClassicGold"] = { {price = 20, faction = {"Loner"}}, {price = 50, faction = {"Duty"}}, {price = 150, faction = {"Military"}} },
	["Base.WristWatch_Left_ClassicGold"] = { {price = 30, faction = {"Loner"}}, {price = 50, faction = {"Duty"}}, {price = 150, faction = {"Military"}} },
	["Base.WristWatch_Right_DigitalBlack"] = { {price = 30, faction = {"Loner"}}, {price = 50, faction = {"Duty"}}, {price = 45, faction = {"Military"}} },
	["Base.WristWatch_Left_DigitalBlack"] = { {price = 30, faction = {"Loner"}}, {price = 40, faction = {"Duty"}}, {price = 60, faction = {"Military"}} },
	["Base.WristWatch_Right_DigitalRed"] = { {price = 14, faction = {"Loner"}}, {price = 40, faction = {"Duty"}}, {price = 30, faction = {"Military"}} },
	["Base.WristWatch_Left_DigitalRed"] = { {price = 7, faction = {"Loner"}}, {price = 35, faction = {"Duty"}}, {price = 55, faction = {"Military"}} },
	["Base.WristWatch_Right_DigitalDress"] = { {price = 25, faction = {"Loner"}}, {price = 200, faction = {"Duty"}}, {price = 250, faction = {"Military"}} },
	["Base.WristWatch_Left_DigitalDress"] = { {price = 22, faction = {"Loner"}}, {price = 200, faction = {"Duty"}}, {price = 250, faction = {"Military"}} },
	--BANDITS/FREEDOM
	["Base.Baker_Tent_6"] = { {price = 120, faction = {"Loner"}}, {price = 200, faction = {"Bandits"}}, {price = 250, faction = {"Freedom"}} },
	["Base.Baker_Tent_5"] = { {price = 120, faction = {"Loner"}}, {price = 200, faction = {"Bandits"}}, {price = 250, faction = {"Freedom"}} },
	["Base.Baker_Tent_4"] = { {price = 120, faction = {"Loner"}}, {price = 200, faction = {"Bandits"}}, {price = 250, faction = {"Freedom"}} },
	["Base.Baker_Tent_3"] = { {price = 120, faction = {"Loner"}}, {price = 200, faction = {"Bandits"}}, {price = 250, faction = {"Freedom"}} },
	["Base.Baker_Tent_2"] = { {price = 120, faction = {"Loner"}}, {price = 200, faction = {"Bandits"}}, {price = 250, faction = {"Freedom"}} },
	["Base.Baker_Tent_1"] = { {price = 120, faction = {"Loner"}}, {price = 200, faction = {"Bandits"}}, {price = 250, faction = {"Freedom"}} },
	["Base.Bass"] = { {price = 20, faction = {"Loner"}}, {price = 30, faction = {"Military"}}, {price = 35, faction = {"Freedom"}} },
	["Base.Catfish"] = { {price = 23, faction = {"Loner"}}, {price = 50, faction = {"Military"}}, {price = 69, faction = {"Freedom"}} },
	["Base.Crappie"] = { {price = 23, faction = {"Loner"}}, {price = 50, faction = {"Military"}}, {price = 69, faction = {"Freedom"}} },
	["Base.Perch"] = { {price = 25, faction = {"Loner"}}, {price = 45, faction = {"Military"}}, {price = 70, faction = {"Freedom"}} },
	["Base.Pike"] = { {price = 56, faction = {"Loner"}}, {price = 105, faction = {"Military"}}, {price = 90, faction = {"Freedom"}} },
	["Base.Panfish"] = { {price = 25, faction = {"Loner"}}, {price = 45, faction = {"Military"}}, {price = 40, faction = {"Freedom"}} },
	["Base.Trout"] =  { {price = 56, faction = {"Loner"}}, {price = 120, faction = {"Military"}}, {price = 120, faction = {"Freedom"}} },
	["Base.DeadBird"] = { {price = 25, faction = {"Loner"}}, {price = 60, faction = {"Bandits"}}, {price = 120, faction = {"Freedom"}} },
	["Base.DeadMouse"] = { {price = 15, faction = {"Loner"}}, {price = 35, faction = {"Bandits"}}, {price = 25, faction = {"Freedom"}} },
	["Base.DeadRabbit"] = { {price = 49, faction = {"Loner"}}, {price = 90, faction = {"Bandits"}}, {price = 80, faction = {"Freedom"}} },
	["Base.DeadRat"] = { {price = 25, faction = {"Loner"}}, {price = 40, faction = {"Bandits"}}, {price = 30, faction = {"Freedom"}} },
	["Base.DeadSquirrel"] = { {price = 25, faction = {"Loner"}}, {price = 45, faction = {"Bandits"}}, {price = 35, faction = {"Freedom"}} },
	["Greenfire.GFGrinder"] = { {price = 100, faction = {"Loner"}}, {price = 200, faction = {"Bandits"}}, {price = 300, faction = {"Freedom"}} },
	["Base.GuitarElectricBlack"] = { {price = 60, faction = {"Loner"}}, {price = 90, faction = {"Bandits"}}, {price = 120, faction = {"Freedom"}} },
	["Base.GuitarElectricBlue"] = { {price = 59, faction = {"Loner"}}, {price = 90, faction = {"Bandits"}}, {price = 120, faction = {"Freedom"}} },
	["Base.GuitarElectricRed"] = { {price = 90, faction = {"Loner"}}, {price = 120, faction = {"Bandits"}}, {price = 150, faction = {"Freedom"}} },
	["Base.Trumpet"] = { {price = 90, faction = {"Loner"}}, {price = 118, faction = {"Bandits"}}, {price = 220, faction = {"Freedom"}} },
	["Base.GuitarAcoustic"] = { {price = 90, faction = {"Loner"}}, {price = 120, faction = {"Bandits"}}, {price = 80, faction = {"Freedom"}} },
	["Base.Bullets357"] = { {price = 4, faction = {"Mercs"}} },
    ["Base.Bullets22"] = { {price = 4, faction = {"Mercs"}} },
    ["Base.Bullets4440"] = { {price = 4, faction = {"Mercs"}} },
    ["Base.Bullets4440"] = { {price = 4, faction = {"Mercs"}} },
    ["Base.9mmCompensator"] = { {price = 190, faction = {"Mercs"}} },
    ["Base.9mmSilencer"] = { {price = 190, faction = {"Mercs"}} },
    ["Base.ShotgunSilencer"] = { {price = 100, faction = {"Mercs"}} },
    ["Base.Laser"] = { {price = 150, faction = {"Mercs"}} },
    ["Base.x2LeupoldScope"] = { {price = 185, faction = {"Mercs"}} },
    ["Base.HeadhunterScope"] = { {price = 240, faction = {"Mercs"}} },
    ["Base.x4-x12Scope"] = { {price = 240, faction = {"Mercs"}} },
    ["Base.x8Scope"] = { {price = 240, faction = {"Mercs"}} },
    ["Base.45Silencer"] = { {price = 190, faction = {"Mercs"}} },
    ["Base.38Silencer"] = { {price = 220, faction = {"Mercs"}} },
    ["Base.308Silencer"] = { {price = 300, faction = {"Mercs"}} },
    ["Base.223Silencer"] = { {price = 190, faction = {"Mercs"}} },
    ["Base.22Silencer"] = { {price = 190, faction = {"Mercs"}} },
    ["Base.Hat_SpoonSkullMask"] = { {price = 300, faction = {"Mercs"}} },
    ["Base.SpoonSkull"] = { {price = 200, faction = {"Mercs"}} },
    ["Base.TvAntique"] = { {price = 350, faction = {"Mercs"}} },
    ["Base.Mov_AntiqueStove"] = { {price = 650, faction = {"Mercs"}} },
    ["Base.Shotgun"] = { {price = 150, faction = {"Mercs"}} },
    ["Base.Mossberg500"] = { {price = 200, faction = {"Mercs"}} },
    ["Base.Mossberg500Tactical"] = { {price = 250, faction = {"Mercs"}} },
    ["Base.ShotgunSawnoff"] = { {price = 150, faction = {"Mercs"}} },
    ["Base.EmptyJar"] = { {price = 1600, faction = {"Mercs"}} },
    ["Base.JarLid"] = { {price = 600, faction = {"Mercs"}} },
    ["Base.Thread"] = { {price = 30, faction = {"Mercs"}} },
    ["UndeadSurvivor.BountyPhoto01"] = { {price = 600, faction = {"Mercs"}} },
    ["UndeadSurvivor.BountyPhoto02"] = { {price = 600, faction = {"Mercs"}} },
    ["UndeadSurvivor.BountyPhoto03"] = { {price = 600, faction = {"Mercs"}} },
    ["UndeadSurvivor.BountyPhoto04"] = { {price = 600, faction = {"Mercs"}} },
    ["UndeadSurvivor.BountyPhoto05"] = { {price = 600, faction = {"Mercs"}} },
    ["UndeadSurvivor.BountyPhoto06"] = { {price = 600, faction = {"Mercs"}} },
    ["UndeadSurvivor.BountyPhoto07"] = { {price = 600, faction = {"Mercs"}} },
    ["UndeadSurvivor.BountyPhoto08"] = { {price = 600, faction = {"Mercs"}} },
    ["UndeadSurvivor.BountyPhoto09"] = { {price = 600, faction = {"Mercs"}} },
    ["UndeadSurvivor.BountyPhoto10"] = { {price = 600, faction = {"Mercs"}} },
	["iMeds.UmifenovirPack"] = { {price = 600, faction = {"Ecologist"}} },
    ["iMeds.Umifenovir"] = { {price = 60, faction = {"Ecologist"}} },
    ["iMeds.NasivionPack"] = { {price = 400, faction = {"Ecologist"}} },
    ["iMeds.Nasivion"] = { {price = 40, faction = {"Ecologist"}} },
    ["iMeds.NaloxonPack"] = { {price = 250, faction = {"Ecologist"}} },
    ["iMeds.Naloxon"] = { {price = 25, faction = {"Ecologist"}} },
    ["iMeds.HemoStopPack"] = { {price = 150, faction = {"Ecologist"}} },
    ["iMeds.HemoStop"] = { {price = 15, faction = {"Ecologist"}} },
    ["iMeds.ErythropoietinPack"] = { {price = 600, faction = {"Ecologist"}} },
    ["iMeds.Erythropoietin"] = { {price = 60, faction = {"Ecologist"}} },
    ["iMeds.ButamiratePack"] = { {price = 300, faction = {"Ecologist"}} },
    ["iMeds.Butamirate"] = { {price = 30, faction = {"Ecologist"}} },
    ["iMeds.BismuthSubsalicylate"] = { {price = 35, faction = {"Ecologist"}} },
    ["iMeds.Alkagin"] = { {price = 200, faction = {"Ecologist"}} },
    ["iMeds.Alkagin"] = { {price = 20, faction = {"Ecologist"}} },
    ["LabItems.CmpFlaskWithLeukocytes"] = { {price = 100, faction = {"Ecologist"}} },
    ["LabItems.CmpFlaskWithAmmoniumSulfate"] = { {price = 100, faction = {"Ecologist"}} },
    ["iMeds.PlasmaBagON"] = { {price = 250, faction = {"Ecologist"}} },
    ["LabItems.MatTaintedBlood"] = { {price = 38, faction = {"Duty"}}, {price = 55, faction = {"Ecologist"}} },
    ["LabItems.MatInfectedBlood"] = { {price = 80, faction = {"Duty"}}, {price = 120, faction = {"Ecologist"}} },
    ["LabItems.LabSyringe"] = { {price = 120, faction = {"Ecologist"}} },
    ["Base.CarBattery1"] = { {price = 9, faction = {"Ecologist"}} },
    ["Base.CarBattery2"] = { {price = 100, faction = {"Ecologist"}} },
    ["Base.CarBattery3"] = { {price = 120, faction = {"Ecologist"}} },
    ["Base.DuctTape"] = { {price = 90, faction = {"Ecologist"}} },
    ["Base.Battery"] = { {price = 70, faction = {"Ecologist"}} },
    ["Base.Flashlight"] = { {price = 100, faction = {"Ecologist"}} },
    ["Base.Sheet"] = { {price = 10, faction = {"Ecologist"}} },
    ["Base.CampingTentKit"] = { {price = 600, faction = {"Ecologist"}} },
    ["Base.SheetMetal"] = { {price = 200, faction = {"Ecologist"}} },
    ["iMeds.Stethoscope"] = { {price = 250, faction = {"Ecologist"}} },
    ["DrHyde.CureNotes"] = { {price = 1500, faction = {"Ecologist"}} },
	["Base.Bracelet_BangleRightGold"] = { {price = 5, faction = {"Loner"}}, {price = 38, faction = {"Duty"}}, {price = 55, faction = {"Bandits"}} },	
	["Base.Bracelet_BangleLeftGold"] =  { {price = 3, faction = {"Loner"}}, {price = 29, faction = {"Duty"}}, {price = 15, faction = {"Bandits"}} },	
	["Base.Bracelet_ChainRightGold"] = { {price = 5, faction = {"Loner"}}, {price = 20, faction = {"Duty"}}, {price = 25, faction = {"Bandits"}} },		
	["Base.Bracelet_ChainLeftGold"] = { {price = 3, faction = {"Loner"}}, {price = 20, faction = {"Duty"}}, {price = 15, faction = {"Bandits"}} },	
	["Base.Bracelet_BangleRightSilver"] = { {price = 2, faction = {"Loner"}}, {price = 12, faction = {"Duty"}}, {price = 15, faction = {"Bandits"}} },	
	["Base.Bracelet_BangleLeftSilver"] = { {price = 2, faction = {"Loner"}}, {price = 10, faction = {"Duty"}}, {price = 40, faction = {"Bandits"}} },	
	["Base.Bracelet_ChainRightSilver"] = { {price = 3, faction = {"Loner"}}, {price = 10, faction = {"Duty"}}, {price = 25, faction = {"Bandits"}} },		
	["Base.Bracelet_ChainLeftSilver"] = { {price = 2, faction = {"Loner"}}, {price = 12, faction = {"Duty"}}, {price = 15, faction = {"Bandits"}} },	
	["Base.BellyButton_DangleGold"] = { {price = 3, faction = {"Loner"}}, {price = 10, faction = {"Duty"}}, {price = 15, faction = {"Bandits"}} },	
	["Base.BellyButton_DangleGoldRuby"] = { {price = 7, faction = {"Loner"}}, {price = 25, faction = {"Duty"}}, {price = 45, faction = {"Bandits"}} },		
	["Base.BellyButton_DangleSilver"] = { {price = 3, faction = {"Loner"}}, {price = 13, faction = {"Duty"}}, {price = 15, faction = {"Bandits"}} },	
	["Base.BellyButton_DangleSilverDiamond"] = { {price = 6, faction = {"Loner"}}, {price = 25, faction = {"Duty"}}, {price = 35, faction = {"Bandits"}} },		
	["Base.BellyButton_RingGold"] = { {price = 3, faction = {"Loner"}}, {price = 10, faction = {"Duty"}}, {price = 15, faction = {"Bandits"}} },	
	["Base.BellyButton_RingGoldDiamond"] = { {price = 15, faction = {"Loner"}}, {price = 76, faction = {"Duty"}}, {price = 120, faction = {"Bandits"}} },		
	["Base.BellyButton_RingGoldRuby"] = { {price = 12, faction = {"Loner"}}, {price = 52, faction = {"Duty"}}, {price = 95, faction = {"Bandits"}} },	
	["Base.BellyButton_RingSilver"] = { {price = 3, faction = {"Loner"}}, {price = 15, faction = {"Duty"}}, {price = 25, faction = {"Bandits"}} },	
	["Base.BellyButton_RingSilverAmethyst"] = { {price = 8, faction = {"Loner"}}, {price = 25, faction = {"Duty"}}, {price = 34, faction = {"Bandits"}} },	
	["Base.BellyButton_RingSilverDiamond"] = { {price = 10, faction = {"Loner"}}, {price = 76, faction = {"Duty"}}, {price = 100, faction = {"Bandits"}} },	
	["Base.BellyButton_RingSilverRuby"] = { {price = 3, faction = {"Loner"}}, {price = 51, faction = {"Duty"}}, {price = 67, faction = {"Bandits"}} },	
	["Base.BellyButton_StudGold"] = { {price = 3, faction = {"Loner"}}, {price = 56, faction = {"Duty"}}, {price = 89, faction = {"Bandits"}} },	
	["Base.BellyButton_StudGoldDiamond"] = { {price = 3, faction = {"Loner"}}, {price = 120, faction = {"Duty"}}, {price = 250, faction = {"Bandits"}} },	
	["Base.BellyButton_StudSilver"] = { {price = 2, faction = {"Loner"}}, {price = 10, faction = {"Duty"}}, {price = 15, faction = {"Bandits"}} },	
	["Base.BellyButton_StudSilverDiamond"] = { {price = 5, faction = {"Loner"}}, {price = 80, faction = {"Duty"}}, {price = 120, faction = {"Bandits"}} },	
	["Base.PetrolCan"] = { {price = 25, faction = {"Loner"}}, {price = 180, faction = {"Military"}}, {price = 180, faction = {"Bandits"}}, {price = 180, faction = {"Ecologist"}}, {price = 180, faction = {"Freedom"}}, {price = 180, faction = {"Duty"}}, {price = 180, faction = {"Mercs"}} },
	["Base.Log"] = { {price = 4, faction = {"Loner"}}, {price = 9, faction = {"Military"}}, {price = 9, faction = {"Bandits"}}, {price = 9, faction = {"Ecologist"}}, {price = 9, faction = {"Freedom"}}, {price = 9, faction = {"Duty"}}, {price = 9, faction = {"Mercs"}} },
	["Base.Plank"] = { {price = 6, faction = {"Loner"}}, {price = 12, faction = {"Military"}}, {price = 12, faction = {"Bandits"}}, {price = 12, faction = {"Ecologist"}}, {price = 12, faction = {"Freedom"}}, {price = 12, faction = {"Duty"}}, {price = 12, faction = {"Mercs"}} },
	["Base.Garbagebag"] = { {price = 25, faction = {"Loner"}}, {price = 50, faction = {"Military"}}, {price = 50, faction = {"Bandits"}}, {price = 50, faction = {"Ecologist"}}, {price = 50, faction = {"Freedom"}}, {price = 50, faction = {"Duty"}}, {price = 50, faction = {"Mercs"}} },
	["Base.RippedSheets"] = { {price = 1, faction = {"Loner"}}, {price = 1, faction = {"Military"}}, {price = 1, faction = {"Bandits"}}, {price = 1, faction = {"Ecologist"}}, {price = 1, faction = {"Freedom"}}, {price = 1, faction = {"Duty"}}, {price = 1, faction = {"Mercs"}} },
	["Base.KitchenKnife"] = { {price = 25, faction = {"Loner"}}, {price = 50, faction = {"Military"}}, {price = 50, faction = {"Bandits"}}, {price = 50, faction = {"Ecologist"}}, {price = 50, faction = {"Freedom"}}, {price = 50, faction = {"Duty"}}, {price = 50, faction = {"Mercs"}} },
	["Base.Cigarettes"] = { {price = 2, faction = {"Loner"}}, {price = 5, faction = {"Military"}}, {price = 5, faction = {"Bandits"}}, {price = 5, faction = {"Ecologist"}}, {price = 5, faction = {"Freedom"}}, {price = 5, faction = {"Duty"}}, {price = 5, faction = {"Mercs"}} },
	["Base.PLGR"] = { {price = 175, faction = {"Loner"}}, {price = 350, faction = {"Military"}}, {price = 350, faction = {"Bandits"}}, {price = 350, faction = {"Ecologist"}}, {price = 350, faction = {"Freedom"}}, {price = 350, faction = {"Duty"}}, {price = 350, faction = {"Mercs"}} },
	["Base.Cigarette"] = { {price = 2, faction = {"Loner"}}, {price = 5, faction = {"Military"}}, {price = 5, faction = {"Bandits"}}, {price = 5, faction = {"Ecologist"}}, {price = 5, faction = {"Freedom"}}, {price = 5, faction = {"Duty"}}, {price = 5, faction = {"Mercs"}} },
	["CanteensAndBottles.JumboJerryCanTank"] = { {price = 145, faction = {"Loner"}}, {price = 290, faction = {"Military"}}, {price = 290, faction = {"Bandits"}}, {price = 290, faction = {"Ecologist"}}, {price = 290, faction = {"Freedom"}}, {price = 290, faction = {"Duty"}}, {price = 290, faction = {"Mercs"}} },
	["Base.HottieZ"] = { {price = 2, faction = {"Loner"}}, {price = 5, faction = {"Military"}}, {price = 5, faction = {"Bandits"}}, {price = 5, faction = {"Ecologist"}}, {price = 5, faction = {"Freedom"}}, {price = 5, faction = {"Duty"}}, {price = 5, faction = {"Mercs"}} },
	["Base.ElectronicsScrap"] = { {price = 7, faction = {"Loner"}}, {price = 15, faction = {"Military"}}, {price = 15, faction = {"Bandits"}}, {price = 15, faction = {"Ecologist"}}, {price = 15, faction = {"Freedom"}}, {price = 15, faction = {"Duty"}},{price = 15, faction = {"Mercs"}} },
	["Base.PillsSleepingTablets"] = { {price = 40, faction = {"Loner"}}, {price = 65, faction = {"Ecologist"}}, {price = 90, faction = {"Bandits"}} },	
	["Base.Wine"] = { {price = 40, faction = {"Loner"}}, {price = 65, faction = {"Military"}}, {price = 90, faction = {"Bandits"}} },	
	["Base.Wine2"] = { {price = 40, faction = {"Loner"}}, {price = 65, faction = {"Military"}}, {price = 90, faction = {"Bandits"}} },
	["Base.BeerCan"] = { {price = 20, faction = {"Loner"}}, {price = 25, faction = {"Military"}}, {price = 60, faction = {"Bandits"}} },
	["MethCooking.MethGood"] = { {price = 30, faction = {"Military"}}, {price = 70, faction = {"Bandits"}}, {price = 30, faction = {"Duty"}} },	
	["MethCooking.MethBad"] = { {price = 15, faction = {"Military"}}, {price = 55, faction = {"Bandits"}}, {price = 15, faction = {"Duty"}} },
	["DrugMod.Meth"] = { {price = 20, faction = {"Military"}}, {price = 65, faction = {"Bandits"}}, {price = 20, faction = {"Duty"}} },
	["DrugMod.LowQualityMeth"] = { {price = 15, faction = {"Military"}}, {price = 40, faction = {"Bandits"}}, {price = 15, faction = {"Duty"}} },
	["DrugMod.MediocreMeth"] = { {price = 35, faction = {"Military"}}, {price = 60, faction = {"Bandits"}}, {price = 35, faction = {"Duty"}} },
	["DrugMod.Cocaine"] = { {price = 25, faction = {"Military"}}, {price = 75, faction = {"Bandits"}}, {price = 25, faction = {"Duty"}} },
	["DrugMod.Crack"] = { {price = 40, faction = {"Military"}}, {price = 90, faction = {"Bandits"}}, {price = 25, faction = {"Duty"}} },
	["Base.Necklace_DogTag"] = { {price = 40, faction = {"Military"}}, {price = 10, faction = {"Bandits"}}, {price = 25, faction = {"Duty"}} },
	["Base.Necklace_Gold"] = { {price = 10, faction = {"Loner"}}, {price = 15, faction = {"Duty"}}, {price = 25, faction = {"Bandits"}} },	
	["Base.Necklace_GoldRuby"] = { {price = 15, faction = {"Loner"}}, {price = 20, faction = {"Duty"}}, {price = 35, faction = {"Bandits"}} },	
	["Base.Necklace_GoldDiamond"] = { {price = 25, faction = {"Loner"}}, {price = 45, faction = {"Duty"}}, {price = 86, faction = {"Bandits"}} },	
	["Base.Necklace_Silver"] = { {price = 2, faction = {"Loner"}}, {price = 10, faction = {"Duty"}}, {price = 15, faction = {"Bandits"}} },
	["Base.Necklace_SilverSapphire"] = { {price = 2, faction = {"Loner"}}, {price = 10, faction = {"Duty"}}, {price = 15, faction = {"Bandits"}} },
	["Base.Necklace_SilverCrucifix"] = { {price = 2, faction = {"Loner"}}, {price = 10, faction = {"Duty"}}, {price = 15, faction = {"Bandits"}} },
	["Base.Necklace_SilverDiamond"] = { {price = 20, faction = {"Loner"}}, {price = 67, faction = {"Duty"}}, {price = 115, faction = {"Bandits"}} },
	["Base.Necklace_Crucifix"] = { {price = 5, faction = {"Loner"}}, {price = 6, faction = {"Duty"}}, {price = 120, faction = {"Bandits"}} },
	["Base.Necklace_YingYang"] = { {price = 12, faction = {"Loner"}}, {price = 10, faction = {"Duty"}}, {price = 149, faction = {"Bandits"}} },
	["Base.Necklace_Pearl"] = { {price = 6, faction = {"Loner"}}, {price = 6, faction = {"Duty"}}, {price = 25, faction = {"Bandits"}} },
	["Base.NecklaceLong_Gold"] = { {price = 4, faction = {"Loner"}}, {price = 6, faction = {"Duty"}}, {price = 12, faction = {"Bandits"}} },
	["Base.NecklaceLong_GoldDiamond"] = { {price = 15, faction = {"Loner"}}, {price = 56, faction = {"Duty"}}, {price = 150, faction = {"Bandits"}} },
	["Base.NecklaceLong_Silver"] = { {price = 5, faction = {"Loner"}}, {price = 6, faction = {"Duty"}}, {price = 120, faction = {"Bandits"}} },
	["Base.NecklaceLong_SilverEmerald"] = { {price = 15, faction = {"Loner"}}, {price = 60, faction = {"Duty"}}, {price = 90, faction = {"Bandits"}} },
	["Base.NecklaceLong_SilverSapphire"] = { {price = 12, faction = {"Loner"}}, {price = 45, faction = {"Duty"}}, {price = 60, faction = {"Bandits"}} },
	["Base.NecklaceLong_SilverDiamond"] = { {price = 50, faction = {"Loner"}}, {price = 120, faction = {"Duty"}}, {price = 139, faction = {"Bandits"}} },
	["Base.NecklaceLong_Amber"] = { {price = 2, faction = {"Loner"}}, {price = 10, faction = {"Duty"}}, {price = 70, faction = {"Bandits"}} },
	["Base.Necklace_Choker"] = { {price = 5, faction = {"Loner"}}, {price = 6, faction = {"Duty"}}, {price = 120, faction = {"Bandits"}} },
	["Base.Necklace_Choker_Sapphire"] = { {price = 1, faction = {"Loner"}}, {price = 4, faction = {"Duty"}}, {price = 6, faction = {"Bandits"}} },
	["Base.Necklace_Choker_Amber"] = { {price = 1, faction = {"Loner"}}, {price = 4, faction = {"Duty"}}, {price = 6, faction = {"Bandits"}} },
	["Base.Necklace_Choker_Diamond"] = { {price = 1, faction = {"Loner"}}, {price = 4, faction = {"Duty"}}, {price = 6, faction = {"Bandits"}} },
	["Base.Locket"] = { {price = 1, faction = {"Loner"}}, {price = 4, faction = {"Duty"}}, {price = 6, faction = {"Bandits"}} },
	["Base.NoseRing_Gold"] = { {price = 12, faction = {"Loner"}}, {price = 25, faction = {"Duty"}}, {price = 42, faction = {"Bandits"}} },
	["Base.NoseRing_Silver"] = { {price = 1, faction = {"Loner"}}, {price = 4, faction = {"Duty"}}, {price = 6, faction = {"Bandits"}} },	
	["Base.NoseStud_Gold"] = { {price = 1, faction = {"Loner"}}, {price = 4, faction = {"Duty"}}, {price = 6, faction = {"Bandits"}} },
	["Base.NoseStud_Silver"] = { {price = 1, faction = {"Loner"}}, {price = 4, faction = {"Duty"}}, {price = 6, faction = {"Bandits"}} },
	["Base.Earring_LoopLrg_Gold"] = { {price = 20, faction = {"Loner"}}, {price = 4, faction = {"Duty"}}, {price = 6, faction = {"Bandits"}} },
	["Base.Earring_LoopLrg_Silver"] =  { {price = 1, faction = {"Loner"}}, {price = 4, faction = {"Duty"}}, {price = 6, faction = {"Bandits"}} },
	["Base.Earring_LoopMed_Silver"] =  { {price = 1, faction = {"Loner"}}, {price = 4, faction = {"Duty"}}, {price = 6, faction = {"Bandits"}} },
	["Base.Earring_LoopMed_Gold"] = { {price = 20, faction = {"Loner"}}, {price = 4, faction = {"Duty"}}, {price = 6, faction = {"Bandits"}} },
	["Base.Earring_LoopSmall_Silver_Both"] = { {price = 1, faction = {"Loner"}}, {price = 4, faction = {"Duty"}}, {price = 6, faction = {"Bandits"}} },
	["Base.Earring_LoopSmall_Gold_Both"] = { {price = 4, faction = {"Loner"}}, {price = 5, faction = {"Duty"}}, {price = 6, faction = {"Bandits"}} },
	["Base.Earring_LoopSmall_Silver_Top"] = { {price = 1, faction = {"Loner"}}, {price = 4, faction = {"Duty"}}, {price = 6, faction = {"Bandits"}} },	
	["Base.Earring_LoopSmall_Gold_Top"] = { {price = 20, faction = {"Loner"}}, {price = 4, faction = {"Duty"}}, {price = 6, faction = {"Bandits"}} },
	["Base.Earring_Stud_Gold"] = { {price = 20, faction = {"Loner"}}, {price = 4, faction = {"Duty"}}, {price = 6, faction = {"Bandits"}} },
	["Base.Earring_Stud_Silver"] = { {price = 1, faction = {"Loner"}}, {price = 4, faction = {"Duty"}}, {price = 6, faction = {"Bandits"}} },
	["Base.Earring_Stone_Sapphire"] =  { {price = 1, faction = {"Loner"}}, {price = 4, faction = {"Duty"}}, {price = 6, faction = {"Bandits"}} },
	["Base.Earring_Stone_Emerald"] =  { {price = 1, faction = {"Loner"}}, {price = 4, faction = {"Duty"}}, {price = 6, faction = {"Bandits"}} },
	["Base.Earring_Stone_Ruby"] =  { {price = 1, faction = {"Loner"}}, {price = 4, faction = {"Duty"}}, {price = 6, faction = {"Bandits"}} },
	["Base.Earring_Pearl"] =  { {price = 1, faction = {"Loner"}}, {price = 4, faction = {"Duty"}}, {price = 6, faction = {"Bandits"}} },
	["Base.Earring_Dangly_Sapphire"] =  { {price = 45, faction = {"Loner"}}, {price = 60, faction = {"Duty"}}, {price = 65, faction = {"Bandits"}} },	
	["Base.Earring_Dangly_Emerald"] =  { {price = 39, faction = {"Loner"}}, {price = 45, faction = {"Duty"}}, {price = 69, faction = {"Bandits"}} },
	["Base.Earring_Dangly_Ruby"] =  { {price = 20, faction = {"Loner"}}, {price = 30, faction = {"Duty"}}, {price = 55, faction = {"Bandits"}} },	
	["Base.Earring_Dangly_Diamond"] =  { {price = 50, faction = {"Loner"}}, {price = 60, faction = {"Duty"}}, {price = 80, faction = {"Bandits"}} },
	["Base.Earring_Dangly_Pearl"] =  { {price = 10, faction = {"Loner"}}, {price = 20, faction = {"Duty"}}, {price = 40, faction = {"Bandits"}} },	
	["Base.Ring_Right_MiddleFinger_Gold"] = { {price = 12, faction = {"Loner"}}, {price = 25, faction = {"Duty"}}, {price = 42, faction = {"Bandits"}} },	 
	["Base.Ring_Left_MiddleFinger_Gold"] = { {price = 12, faction = {"Loner"}}, {price = 25, faction = {"Duty"}}, {price = 42, faction = {"Bandits"}} },	
	["Base.Ring_Right_RingFinger_Gold"] = { {price = 12, faction = {"Loner"}}, {price = 25, faction = {"Duty"}}, {price = 42, faction = {"Bandits"}} },
	["Base.Ring_Left_RingFinger_Gold"] = { {price = 12, faction = {"Loner"}}, {price = 25, faction = {"Duty"}}, {price = 42, faction = {"Bandits"}} },
	["Base.Ring_Right_MiddleFinger_GoldDiamond"] = { {price = 12, faction = {"Loner"}}, {price = 25, faction = {"Duty"}}, {price = 70, faction = {"Bandits"}} },
	["Base.Ring_Left_MiddleFinger_GoldDiamond"] = { {price = 12, faction = {"Loner"}}, {price = 45, faction = {"Duty"}}, {price = 80, faction = {"Bandits"}} },	
	["Base.Ring_Right_RingFinger_GoldDiamond"] = { {price = 12, faction = {"Loner"}}, {price = 34, faction = {"Duty"}}, {price = 70, faction = {"Bandits"}} },
	["Base.Ring_Left_RingFinger_GoldDiamond"] = { {price = 12, faction = {"Loner"}}, {price = 35, faction = {"Duty"}}, {price = 56, faction = {"Bandits"}} },
	["Base.Ring_Right_MiddleFinger_GoldRuby"] = { {price = 12, faction = {"Loner"}}, {price = 25, faction = {"Duty"}}, {price = 56, faction = {"Bandits"}} },
	["Base.Ring_Left_MiddleFinger_GoldRuby"] = { {price = 12, faction = {"Loner"}}, {price = 40, faction = {"Duty"}}, {price = 45, faction = {"Bandits"}} },	
	["Base.Ring_Right_RingFinger_GoldRuby"] = { {price = 12, faction = {"Loner"}}, {price = 25, faction = {"Duty"}}, {price = 42, faction = {"Bandits"}} },	
	["Base.Ring_Left_RingFinger_GoldRuby"] = { {price = 12, faction = {"Loner"}}, {price = 25, faction = {"Duty"}}, {price = 42, faction = {"Bandits"}} },
	["Base.Ring_Right_MiddleFinger_Silver"] = { {price = 1, faction = {"Loner"}}, {price = 4, faction = {"Duty"}}, {price = 6, faction = {"Bandits"}} },
	["Base.Ring_Left_MiddleFinger_Silver"] = { {price = 1, faction = {"Loner"}}, {price = 4, faction = {"Duty"}}, {price = 6, faction = {"Bandits"}} },
	["Base.Ring_Right_RingFinger_Silver"] = { {price = 1, faction = {"Loner"}}, {price = 4, faction = {"Duty"}}, {price = 6, faction = {"Bandits"}} },	
	["Base.Ring_Left_RingFinger_Silver"] = { {price = 1, faction = {"Loner"}}, {price = 4, faction = {"Duty"}}, {price = 6, faction = {"Bandits"}} },	
	["Base.Ring_Right_MiddleFinger_SilverDiamond"] = { {price = 1, faction = {"Loner"}}, {price = 4, faction = {"Duty"}}, {price = 6, faction = {"Bandits"}} },	
	["Base.Ring_Left_MiddleFinger_SilverDiamond"] = { {price = 1, faction = {"Loner"}}, {price = 4, faction = {"Duty"}}, {price = 6, faction = {"Bandits"}} },	
	["Base.Ring_Right_RingFinger_SilverDiamond"] = { {price = 1, faction = {"Loner"}}, {price = 4, faction = {"Duty"}}, {price = 6, faction = {"Bandits"}} },	
	["Base.Ring_Left_RingFinger_SilverDiamond"] = { {price = 1, faction = {"Loner"}}, {price = 4, faction = {"Duty"}}, {price = 6, faction = {"Bandits"}} },	
	["Base.WeddingRing_Man"] =  { {price = 1, faction = {"Loner"}}, {price = 4, faction = {"Duty"}}, {price = 6, faction = {"Bandits"}} },
	["Base.WeddingRing_Woman"] =  { {price = 1, faction = {"Loner"}}, {price = 4, faction = {"Duty"}}, {price = 6, faction = {"Bandits"}} },
	["iMeds.SyringeWithNeedle"] = { {price = 5, faction = {"Loner"}}, {price = 50, faction = {"Duty"}}, {price = 75, faction = {"Bandits"}} },
	["iMeds.SyringePack"] = { {price = 120, faction = {"Loner"}}, {price = 500, faction = {"Duty"}}, {price = 650, faction = {"Bandits"}} },
	["iMeds.UnknownPack"] = { {price = 90, faction = {"Loner"}}, {price = 500, faction = {"Duty"}}, {price = 750, faction = {"Bandits"}} },
	["Base.BeerBottle"] = { {price = 30, faction = {"Bandits"}} },	
	["Base.BeerCan"] = { {price = 30, faction = {"Bandits"}} },
	["Greenfire.FreshUnCanna"] = { {price = 9, faction = {"Bandits"}} },
	["Base.PillsSleepingTablets"] = { {price = 90, faction = {"Bandits"}} },	
	["ZBR.TripleSec"] = { {price = 30, faction = {"Bandits"}} },
	["iMeds.Morphine"] = { {price = 120, faction = {"Bandits"}} },
	["iMeds.MorphinePack"] = { {price = 850, faction = {"Bandits"}} },
	["Base.WhiskeyFull"] = { {price = 45, faction = {"Bandits"}} },
	["iMeds.Needle"] = { {price = 45, faction = {"Bandits"}} },
	["Base.PokerChips"] = { {price = 1, faction = {"Bandits"}} },
	["ZBR.Martini"] = { {price = 100, faction = {"Bandits"}} },
	["ZBR.LIIT"] = { {price = 120, faction = {"Bandits"}} },
	["ZBR.KYCoffee"] = { {price = 95, faction = {"Bandits"}} },
	["ZBR.InsaneBloodyMary"] = { {price = 150, faction = {"Bandits"}} },
	["ZBR.ImprovedBloodyMary"] = { {price = 120, faction = {"Bandits"}} },
	["ZBR.Highball"] = { {price = 40, faction = {"Bandits"}} },
	["ZBR.Gin"] = { {price = 35, faction = {"Bandits"}} },
	["ZBR.Flip"] = { {price = 45, faction = {"Bandits"}} },
	["ZBR.Rum"] = { {price = 85, faction = {"Bandits"}} },
	["ZBR.Daiquiri"] = { {price = 25, faction = {"Bandits"}} },
	["ZBR.Cocktail"] = { {price = 75, faction = {"Bandits"}} },
	["ZBR.Brandy"] = { {price = 42, faction = {"Bandits"}} },
	["ZBR.BloodyMary"] = { {price = 110, faction = {"Bandits"}} },
	["ZBR.Bitters"] = { {price = 55, faction = {"Bandits"}} },
	["ZBR.Moonshine"] = { {price = 220, faction = {"Bandits"}} },
	["ZBR.Sidecar"] = { {price = 85, faction = {"Bandits"}} },
	["ZBR.Seltzer"] = { {price = 60, faction = {"Bandits"}} },
	["ZBR.Tequila"] = { {price = 80, faction = {"Bandits"}} },
	["stalkerfood.CossacksVodka"] = { {price = 5, faction = {"Loner"}}, {price = 50, faction = {"Bandits"}}, {price = 65, faction = {"Military"}} },
	["Base.Cigarettes"] = { {price = 5, faction = {"Loner"}}, {price = 20, faction = {"Bandits"}}, {price = 30, faction = {"Military"}} },
	["stalker.ArtifactWrenched"] =  { {price = 30, faction = {"Ecologist"}}, {price = 50, faction = {"Freedom"}}, {price = 20, faction = {"Duty"}} },
	["stalker.ArtifactUrchin"] = { {price = 30, faction = {"Ecologist"}}, {price = 54, faction = {"Freedom"}}, {price = 24, faction = {"Duty"}} },
	["stalker.ArtifactSun"] = { {price = 200, faction = {"Ecologist"}}, {price = 250, faction = {"Freedom"}}, {price = 120, faction = {"Duty"}} },
	["stalker.ArtifactStoneFlower"] = { {price = 20, faction = {"Ecologist"}}, {price = 50, faction = {"Freedom"}}, {price = 15, faction = {"Duty"}} },
	["stalker.ArtifactSourpuss"] = { {price = 70, faction = {"Ecologist"}}, {price = 95, faction = {"Freedom"}}, {price = 65, faction = {"Duty"}} },
	["stalker.ArtifactSoul"] = { {price = 120, faction = {"Ecologist"}}, {price = 200, faction = {"Freedom"}}, {price = 90, faction = {"Duty"}} },
	["stalker.ArtifactSnowflake"] = { {price = 220, faction = {"Ecologist"}}, {price = 260, faction = {"Freedom"}}, {price = 150, faction = {"Duty"}} },
	["stalker.ArtifactSignet"] = { {price = 170, faction = {"Ecologist"}}, {price = 184, faction = {"Freedom"}}, {price = 150, faction = {"Duty"}} },
	["stalker.ArtifactSeraphim"] = { {price = 70, faction = {"Ecologist"}}, {price = 120, faction = {"Freedom"}}, {price = 50, faction = {"Duty"}} },
	["stalker.ArtifactPhantomStar"] = { {price = 220, faction = {"Ecologist"}}, {price = 280, faction = {"Freedom"}}, {price = 150, faction = {"Duty"}} },
	["stalker.ArtifactPellicle"] = { {price = 200, faction = {"Ecologist"}}, {price = 330, faction = {"Freedom"}}, {price = 170, faction = {"Duty"}} },
	["stalker.ArtifactMamasBeads"] = { {price = 450, faction = {"Ecologist"}}, {price = 1000, faction = {"Freedom"}}, {price = 250, faction = {"Duty"}} },
	["stalker.ArtifactHeart"] = { {price = 450, faction = {"Ecologist"}}, {price = 650, faction = {"Freedom"}}, {price = 399, faction = {"Duty"}} },
	["stalker.ArtifactFountain"] = { {price = 420, faction = {"Ecologist"}}, {price = 450, faction = {"Freedom"}}, {price = 344, faction = {"Duty"}} },
	["stalker.ArtifactFirefly"] = { {price = 100, faction = {"Ecologist"}}, {price = 167, faction = {"Freedom"}}, {price = 130, faction = {"Duty"}} },
	["stalker.ArtifactEye"] = { {price = 18, faction = {"Ecologist"}}, {price = 190, faction = {"Freedom"}}, {price = 60, faction = {"Duty"}} },
	["stalker.ArtifactCrystalThorn"] = { {price = 800, faction = {"Ecologist"}}, {price = 1500, faction = {"Freedom"}}, {price = 670, faction = {"Duty"}} },
	["stalker.ArtifactCrystal"] = { {price = 2000, faction = {"Ecologist"}}, {price = 2700, faction = {"Freedom"}}, {price = 1700, faction = {"Duty"}} },
	["stalker.ArtifactChain"] = { {price = 200, faction = {"Ecologist"}}, {price = 250, faction = {"Freedom"}}, {price = 170, faction = {"Duty"}} },
	["stalker.ArtifactCell"] = { {price = 250, faction = {"Ecologist"}}, {price = 420, faction = {"Freedom"}}, {price = 300, faction = {"Duty"}} },
	["Base.PetrolCan"] = { {price = 25, faction = {"Loner"}}, {price = 180, faction = {"Military"}}, {price = 180, faction = {"Bandits"}}, {price = 180, faction = {"Ecologist"}}, {price = 180, faction = {"Freedom"}}, {price = 180, faction = {"Duty"}},{price = 180, faction = {"Mercs"}} },
	["Base.Log"] = { {price = 4, faction = {"Loner"}}, {price = 9, faction = {"Military"}}, {price = 9, faction = {"Bandits"}}, {price = 9, faction = {"Ecologist"}}, {price = 9, faction = {"Freedom"}}, {price = 9, faction = {"Duty"}},{price = 9, faction = {"Mercs"}} },
	["Base.Plank"] = { {price = 6, faction = {"Loner"}}, {price = 12, faction = {"Military"}}, {price = 12, faction = {"Bandits"}}, {price = 12, faction = {"Ecologist"}}, {price = 12, faction = {"Freedom"}}, {price = 12, faction = {"Duty"}}, {price = 12, faction = {"Mercs"}} },
	["Base.Garbagebag"] = { {price = 25, faction = {"Loner"}}, {price = 50, faction = {"Military"}}, {price = 50, faction = {"Bandits"}}, {price = 50, faction = {"Ecologist"}}, {price = 50, faction = {"Freedom"}}, {price = 50, faction = {"Duty"}}, {price = 50, faction = {"Mercs"}} },
	["Base.RippedSheets"] = { {price = 1, faction = {"Loner"}}, {price = 1, faction = {"Military"}}, {price = 1, faction = {"Bandits"}}, {price = 1, faction = {"Ecologist"}}, {price = 1, faction = {"Freedom"}}, {price = 1, faction = {"Duty"}}, {price = 1, faction = {"Mercs"}} },
	["Base.KitchenKnife"] = { {price = 25, faction = {"Loner"}}, {price = 50, faction = {"Military"}}, {price = 50, faction = {"Bandits"}}, {price = 50, faction = {"Ecologist"}}, {price = 50, faction = {"Freedom"}}, {price = 50, faction = {"Duty"}}, {price = 50, faction = {"Mercs"}} },
	["Base.Cigarettes"] = { {price = 2, faction = {"Loner"}}, {price = 5, faction = {"Military"}}, {price = 5, faction = {"Bandits"}}, {price = 5, faction = {"Ecologist"}}, {price = 5, faction = {"Freedom"}}, {price = 5, faction = {"Duty"}}, {price = 5, faction = {"Mercs"}} },
	["Base.PLGR"] = { {price = 175, faction = {"Loner"}}, {price = 350, faction = {"Military"}}, {price = 350, faction = {"Bandits"}}, {price = 350, faction = {"Ecologist"}}, {price = 350, faction = {"Freedom"}}, {price = 350, faction = {"Duty"}}, {price = 350, faction = {"Mercs"}} },
	["Base.Cigarette"] = { {price = 2, faction = {"Loner"}}, {price = 5, faction = {"Military"}}, {price = 5, faction = {"Bandits"}}, {price = 5, faction = {"Ecologist"}}, {price = 5, faction = {"Freedom"}}, {price = 5, faction = {"Duty"}}, {price = 5, faction = {"Mercs"}} },
	["CanteensAndBottles.JumboJerryCanTank"] = { {price = 145, faction = {"Loner"}}, {price = 290, faction = {"Military"}}, {price = 290, faction = {"Bandits"}}, {price = 290, faction = {"Ecologist"}}, {price = 290, faction = {"Freedom"}}, {price = 290, faction = {"Duty"}}, {price = 290, faction = {"Mercs"}} },
	["Base.HottieZ"] = { {price = 2, faction = {"Loner"}}, {price = 5, faction = {"Military"}}, {price = 5, faction = {"Bandits"}}, {price = 5, faction = {"Ecologist"}}, {price = 5, faction = {"Freedom"}}, {price = 5, faction = {"Duty"}}, {price = 5, faction = {"Mercs"}} },
	["Base.ElectronicsScrap"] = { {price = 7, faction = {"Loner"}}, {price = 15, faction = {"Military"}}, {price = 15, faction = {"Bandits"}}, {price = 15, faction = {"Ecologist"}}, {price = 15, faction = {"Freedom"}}, {price = 15, faction = {"Duty"}}, {price = 15, faction = {"Mercs"}} },
	["Base.ScrapMetal"] = { {price = 10, faction = {"Loner"}}, {price = 20, faction = {"Military"}}, {price = 20, faction = {"Bandits"}}, {price = 20, faction = {"Ecologist"}}, {price = 20, faction = {"Freedom"}}, {price = 20, faction = {"Duty"}}, {price = 20, faction = {"Mercs"}} },
    ["Base.SmallSheetMetal"] = { {price = 35, faction = {"Loner"}}, {price = 70, faction = {"Military"}}, {price = 70, faction = {"Bandits"}}, {price = 70, faction = {"Ecologist"}}, {price = 70, faction = {"Freedom"}}, {price = 70, faction = {"Duty"}}, {price = 70, faction = {"Mercs"}} },
    ["Base.MetalBar"] = { {price = 45, faction = {"Loner"}}, {price = 90, faction = {"Military"}}, {price = 90, faction = {"Bandits"}}, {price = 90, faction = {"Ecologist"}}, {price = 90, faction = {"Freedom"}}, {price = 90, faction = {"Duty"}}, {price = 90, faction = {"Mercs"}} },
    ["Base.MetalPipe"] = { {price = 100, faction = {"Loner"}}, {price = 100, faction = {"Military"}}, {price = 100, faction = {"Bandits"}}, {price = 100, faction = {"Ecologist"}}, {price = 100, faction = {"Freedom"}}, {price = 100, faction = {"Duty"}}, {price = 100, faction = {"Mercs"}} },
    ["Base.SandBag"] = { {price = 20, faction = {"Loner"}}, {price = 40, faction = {"Military"}}, {price = 40, faction = {"Bandits"}}, {price = 40, faction = {"Ecologist"}}, {price = 40, faction = {"Freedom"}}, {price = 40, faction = {"Duty"}}, {price = 40, faction = {"Mercs"}} },
    ["Base.GravelBag"] = { {price = 25, faction = {"Loner"}}, {price = 50, faction = {"Military"}}, {price = 50, faction = {"Bandits"}}, {price = 50, faction = {"Ecologist"}}, {price = 50, faction = {"Freedom"}}, {price = 50, faction = {"Duty"}}, {price = 50, faction = {"Mercs"}} },
    ["Base.Solvent"] = { {price = 75, faction = {"Loner"}}, {price = 150, faction = {"Military"}}, {price = 150, faction = {"Bandits"}}, {price = 150, faction = {"Ecologist"}}, {price = 150, faction = {"Freedom"}}, {price = 150, faction = {"Duty"}}, {price = 150, faction = {"Mercs"}} },
    ["Greenfire.Cannabis"] = { {price = 5, faction = {"Military"}}, {price = 7, faction = {"Bandits"}}, {price = 15, faction = {"Freedom"}}, {price = 5, faction = {"Duty"}} },
    ["Greenfire.Joint"] = { {price = 5, faction = {"Military"}}, {price = 12, faction = {"Bandits"}}, {price = 24, faction = {"Freedom"}}, {price = 5, faction = {"Duty"}} },
    ["Greenfire.KiefJoint"] = { {price = 10, faction = {"Military"}}, {price = 20, faction = {"Bandits"}}, {price = 33, faction = {"Freedom"}}, {price = 10, faction = {"Duty"}} },
	["Greenfire.KgCannabis"] = { {price = 5000, faction = {"Military"}}, {price = 10000, faction = {"Bandit"}}, {price = 15000, faction = {"Freedom"}}, {price = 5000, faction = {"Duty"}} },
	["Base.HumanFlesh"] = { {price = 500, faction = {"Monolith"}} },
	["Base.ZombieFlesh"] = { {price = 60, faction = {"Monolith"}} },
	["Base.HumanLiver"] = { {price = 300, faction = {"Monolith"}} }
}

