--Item definition for selling stuff, if the item is not here the default price will be Shop.defaultPrice 
-- and broken price will be Shop.defaultPriceBroken

-- If a item has a sell price equal to 0 it won't show up in the ShopUI window
Shop.defaultPriceBroken = 1 -- Default sell price for broken items
Shop.defaultPrice = 0 -- Default sell price for items 
Shop.SellisBlacklist = false -- Use Shop.Sell as blacklist
Shop.SellisWhitelist = true -- Use Shop.Sell as whitelist
-- If Shop.SellisBlacklist and Shop.SellisWhitelist set to false every item is sellable
Shop.Sell = {
	
	["Base.GunPowder"] = { price = 3, faction = {"Military"} },
	["Base.GunToolKit"] = { price = 140, faction = {"Military"} },
	["Base.Bass"] = { price = 60, faction = {"Military"} },
	["Base.Catfish"] = { price = 120, faction = {"Military"} },
	["Base.Perch"] = { price = 70, faction = {"Military"} },
	["Base.Crappie"] = { price = 30, faction = {"Military"} },
	["Base.Sunfish"] = { price = 90, faction = {"Military"} },
	["Base.Trout"] = { price = 30, faction = {"Military"} },
	["Greenfire.DryBTobacco"] = { price = 1, faction = {"Military"} },
	["Base.TinnedBeans"] = { price = 25, faction = {"Military"} },
	["Base.CannedCarrots"] = { price = 25, faction = {"Military"} },
	["Base.CannedChili"] = { price = 25, faction = {"Military"} },
	["Base.CannedCorn"] = { price = 25, faction = {"Military"} },
	["Base.CannedCornedBeef"] = { price = 25, faction = {"Military"} },
	["Base.CannedFruitCocktail"] = { price = 25, faction = {"Military"} },
	["Base.CannedMushroomSoup"] = { price = 25, faction = {"Military"} },
	["Base.CannedPeas"] = { price = 25, faction = {"Military"} },
	["Base.CannedPeaches"] = { price = 25, faction = {"Military"} },
	["Base.CannedPineapple"] = { price = 25, faction = {"Military"} },
	["Base.CannedPotato2"] = { price = 25, faction = {"Military"} },
	["Base.CannedSardines"] = { price = 25, faction = {"Military"} },
	["Base.TinnedSoup"] = { price = 25, faction = {"Military"} },
	["Base.CannedBolognese"] = { price = 25, faction = {"Military"} },
	["Base.CannedMilk"] = { price = 25, faction = {"Military"} },
	["Base.CannedTomato2"] = { price = 25, faction = {"Military"} },
	["Base.CannedCarrots2"] = { price = 25, faction = {"Military"} },
	["Base.TunaTin"] = { price = 25, faction = {"Military"} },
	["Base.Dogfood"] = { price = 25, faction = {"Military"} },
	["Base.WhiskeyFull"] = { price = 100, faction = {"Military"} },
	["Greenfire.Tobacco"] = { price = 3, faction = {"Military"} },
	["Base.WristWatch_Right_ClassicBlack"] = { price = 20, faction = {"Military"} },
	["Base.WristWatch_Left_ClassicBlack"] = { price = 20, faction = {"Military"} },
	["Base.WristWatch_Right_ClassicBrown"] = { price = 20, faction = {"Military"} },
	["Base.WristWatch_Left_ClassicBrown"] = { price = 20, faction = {"Military"} },
	["Base.WristWatch_Right_ClassicMilitary"] = { price = 100, faction = {"Military"} },
	["Base.WristWatch_Left_ClassicMilitary"] = { price = 100, faction = {"Military"} },
	["Base.WristWatch_Right_ClassicGold"] = { price = 50, faction = {"Military"} },
	["Base.WristWatch_Left_ClassicGold"] = { price = 50, faction = {"Military"} },
	["Base.WristWatch_Right_DigitalBlack"] = { price = 30, faction = {"Military"} },
	["Base.WristWatch_Left_DigitalBlack"] = { price = 30, faction = {"Military"} },
	["Base.WristWatch_Right_DigitalRed"] = { price = 30, faction = {"Military"} },
	["Base.WristWatch_Left_DigitalRed"] = { price = 30, faction = {"Military"} },
	["Base.WristWatch_Right_DigitalDress"] = { price = 50, faction = {"Military"} },
	["Base.WristWatch_Left_DigitalDress"] = { price = 50, faction = {"Military"} },

	--BANDITS/FREEDOM
	["Base.DeadMouse"] = { price = 30, faction = {"Bandits", "Freedom"} },
	["Base.DeadRabbit"] = { price = 90, faction = {"Bandits", "Freedom"} },
	["Base.DeadRat"] = { price = 30, faction = {"Bandits", "Freedom"} },
	["Base.DeadSquirrel"] = { price = 120, faction = {"Bandits", "Freedom"} },
	["Base.HottieZ"] = { price = 2500, faction = {"Bandits", "Freedom"} },
	["Greenfire.GFGrinder"] = { price = 300, faction = {"Bandits", "Freedom"} },
	["Base.GuitarElectricBlack"] = { price = 200, faction = {"Bandits", "Freedom"} },
	["Base.GuitarElectricBlue"] = { price = 90, faction = {"Bandits", "Freedom"} },
	["Base.GuitarElectricRed"] = { price = 150, faction = {"Bandits", "Freedom"} },
	["Base.Trumpet"] = { price = 120, faction = {"Bandits", "Freedom"} },
	["Base.GuitarAcoustic"] = { price = 120, faction = {"Bandits", "Freedom"} },

	-- Mercs
	["Base.Hat_SpoonSkullMask"] = { price = 300, faction = {"Mercs"} },
	["Base.SpoonSkull"] = { price = 200, faction = {"Mercs"} },
	["Base.TvAntique"] = { price = 350, faction = {"Mercs"} },
	["Base.Mov_AntiqueStove"] = { price = 750, faction = {"Mercs"} },
	["Base.Shotgun"] = { price = 150, faction = {"Mercs"} },
	["Base.Mossberg500"] = { price = 200, faction = {"Mercs"} },
	["Base.Mossberg500Tactical"] = { price = 250, faction = {"Mercs"} },
	["Base.ShotgunSawnoff"] = { price = 150, faction = {"Mercs"} },
	["Base.EmptyJar"] = { price = 600, faction = {"Mercs"} },
	["Base.Thread"] = { price = 30, faction = {"Mercs"} },
	["Base.Cigarettes"] = { price = 5, faction = {"Mercs"} },
	["Base.Cigarette"] = { price = 5, faction = {"Mercs"} },
	
		
	--BANDITS
	
	["Base.PillsSleepingTablets"] = { price = 95, faction = {"Bandits"} },
	["Base.Wine"] = { price = 65, faction = {"Bandits"} },
	["Base.Wine2"] = { price = 65, faction = {"Bandits"} },
	["Base.BeerCan"] = { price = 50, faction = {"Bandits"} },
	["MethCooking.MethGood"] = { price = 25, faction = {"Bandits"} },
	["MethCooking.MethBad"] = { price = 5, faction = {"Bandits"} },
	["DrugMod.Meth"] = { price = 90, faction = {"Bandits"} },
	["DrugMod.LowQualityMeth"] = { price = 40, faction = {"Bandits"} },
	["DrugMod.MediocreMeth"] = { price = 60, faction = {"Bandits"} },
	["DrugMod.Cocaine"] = { price = 45, faction = {"Bandits"} },
	["DrugMod.Crack"] = { price = 90, faction = {"Bandits"} },
	["Base.Necklace_DogTag"] = { price = 10, faction = {"Bandits"} }, 
	["Base.Necklace_Gold"] = { price = 20, faction = {"Bandits"} },
	["Base.Necklace_GoldRuby"] = { price = 20, faction = {"Bandits"} },
	["Base.Necklace_GoldDiamond"] = { price = 20, faction = {"Bandits"} },
	["Base.Necklace_Silver"] = { price = 3, faction = {"Bandits"} },
	["Base.Necklace_SilverSapphire"] = { price = 3, faction = {"Bandits"} },
	["Base.Necklace_SilverCrucifix"] = { price = 3, faction = {"Bandits"} },
	["Base.Necklace_SilverDiamond"] = { price = 3, faction = {"Bandits"} },
	["Base.Necklace_Crucifix"] = { price = 3, faction = {"Bandits"} },
	["Base.Necklace_YingYang"] = { price = 3, faction = {"Bandits"} },
	["Base.Necklace_Pearl"] = { price = 3, faction = {"Bandits"} },
	["Base.NecklaceLong_Gold"] = { price = 20, faction = {"Bandits"} },
	["Base.NecklaceLong_GoldDiamond"] = { price = 20, faction = {"Bandits"} },
	["Base.NecklaceLong_Silver"] = { price = 3, faction = {"Bandits"} },
	["Base.NecklaceLong_SilverEmerald"] = { price = 5, faction = {"Bandits"} },
	["Base.NecklaceLong_SilverSapphire"] = { price = 5, faction = {"Bandits"} },
	["Base.NecklaceLong_SilverDiamond"] = { price = 5, faction = {"Bandits"} },
	["Base.NecklaceLong_Amber"] = { price = 3, faction = {"Bandits"} },
	["Base.Necklace_Choker"] = { price = 3, faction = {"Bandits"} },
	["Base.Necklace_Choker_Sapphire"] = { price = 3, faction = {"Bandits"} },
	["Base.Necklace_Choker_Amber"] = { price = 3, faction = {"Bandits"} },
	["Base.Necklace_Choker_Diamond"] = { price = 3, faction = {"Bandits"} },
	["Base.Locket"] = { price = 3, faction = {"Bandits"} },	
	["Base.NoseRing_Gold"] = { price = 20, faction = {"Bandits"} },	
	["Base.NoseRing_Silver"] = { price = 1, faction = {"Bandits"} },	
	["Base.NoseStud_Gold"] = { price = 20, faction = {"Bandits"} },	
	["Base.NoseStud_Silver"] = { price = 1, faction = {"Bandits"} },	
	["Base.Earring_LoopLrg_Gold"] = { price = 20, faction = {"Bandits"} },	
	["Base.Earring_LoopLrg_Silver"] = { price = 1, faction = {"Bandits"} },	
	["Base.Earring_LoopMed_Silver"] = { price = 1, faction = {"Bandits"} },	
	["Base.Earring_LoopMed_Gold"] = { price = 20, faction = {"Bandits"} },	
	["Base.Earring_LoopSmall_Silver_Both"] = { price = 1, faction = {"Bandits"} },	
	["Base.Earring_LoopSmall_Gold_Both"] = { price = 20, faction = {"Bandits"} },	
	["Base.Earring_LoopSmall_Silver_Top"] = { price = 1, faction = {"Bandits"} },	
	["Base.Earring_LoopSmall_Gold_Top"] = { price = 20, faction = {"Bandits"} },	
	["Base.Earring_Stud_Gold"] = { price = 20, faction = {"Bandits"} },	
	["Base.Earring_Stud_Silver"] = { price = 1, faction = {"Bandits"} },	
	["Base.Earring_Stone_Sapphire"] = { price = 2, faction = {"Bandits"} },	
	["Base.Earring_Stone_Emerald"] = { price = 2, faction = {"Bandits"} },	
	["Base.Earring_Stone_Ruby"] = { price = 2, faction = {"Bandits"} },	
	["Base.Earring_Pearl"] = { price = 1, faction = {"Bandits"} },	
	["Base.Earring_Dangly_Sapphire"] = { price = 2, faction = {"Bandits"} },	
	["Base.Earring_Dangly_Emerald"] = { price = 2, faction = {"Bandits"} },	
	["Base.Earring_Dangly_Ruby"] = { price = 2, faction = {"Bandits"} },	
	["Base.Earring_Dangly_Diamond"] = { price = 2, faction = {"Bandits"} },	
	["Base.Earring_Dangly_Pearl"] = { price = 2, faction = {"Bandits"} },	
	["Base.Ring_Right_MiddleFinger_Gold"] = { price = 20, faction = {"Bandits"} },	 
	["Base.Ring_Left_MiddleFinger_Gold"] = { price = 20, faction = {"Bandits"} },	
	["Base.Ring_Right_RingFinger_Gold"] = { price = 20, faction = {"Bandits"} },	
	["Base.Ring_Left_RingFinger_Gold"] = { price = 20, faction = {"Bandits"} },	
	["Base.Ring_Right_MiddleFinger_GoldDiamond"] = { price = 20, faction = {"Bandits"} },	
	["Base.Ring_Left_MiddleFinger_GoldDiamond"] = { price = 20, faction = {"Bandits"} },	
	["Base.Ring_Right_RingFinger_GoldDiamond"] = { price = 20, faction = {"Bandits"} },	
	["Base.Ring_Left_RingFinger_GoldDiamond"] = { price = 20, faction = {"Bandits"} },	
	["Base.Ring_Right_MiddleFinger_GoldRuby"] = { price = 20, faction = {"Bandits"} },	
	["Base.Ring_Left_MiddleFinger_GoldRuby"] = { price = 20, faction = {"Bandits"} },	
	["Base.Ring_Right_RingFinger_GoldRuby"] = { price = 20, faction = {"Bandits"} },	
	["Base.Ring_Left_RingFinger_GoldRuby"] = { price = 20, faction = {"Bandits"} },	
	["Base.Ring_Right_MiddleFinger_Silver"] = { price = 1, faction = {"Bandits"} },	
	["Base.Ring_Left_MiddleFinger_Silver"] = { price = 1, faction = {"Bandits"} },	
	["Base.Ring_Right_RingFinger_Silver"] = { price = 1, faction = {"Bandits"} },	
	["Base.Ring_Left_RingFinger_Silver"] = { price = 1, faction = {"Bandits"} },	
	["Base.Ring_Right_MiddleFinger_SilverDiamond"] = { price = 2, faction = {"Bandits"} },	
	["Base.Ring_Left_MiddleFinger_SilverDiamond"] = { price = 2, faction = {"Bandits"} },	
	["Base.Ring_Right_RingFinger_SilverDiamond"] = { price = 2, faction = {"Bandits"} },	
	["Base.Ring_Left_RingFinger_SilverDiamond"] = { price = 2, faction = {"Bandits"} },	
	["Base.WeddingRing_Man"] = { price = 1, faction = {"Bandits"} },	
	["Base.WeddingRing_Woman"] = { price = 1, faction = {"Bandits"} },	
	["Base.WristWatch_Right_ClassicGold"] = { price = 20, faction = {"Bandits"} },	
	["Base.WristWatch_Left_ClassicGold"] = { price = 20, faction = {"Bandits"} },	
	["Base.Bracelet_BangleRightGold"] = { price = 3, faction = {"Bandits"} },	
	["Base.Bracelet_BangleLeftGold"] = { price = 3, faction = {"Bandits"} },	
	["Base.Bracelet_ChainRightGold"] = { price = 20, faction = {"Bandits"} },	
	["Base.Bracelet_ChainLeftGold"] = { price = 20, faction = {"Bandits"} },	
	["Base.Bracelet_BangleRightSilver"] = { price = 3, faction = {"Bandits"} },	
	["Base.Bracelet_BangleLeftSilver"] = { price = 3, faction = {"Bandits"} },	
	["Base.Bracelet_ChainRightSilver"] = { price = 3, faction = {"Bandits"} },	
	["Base.Bracelet_ChainLeftSilver"] = { price = 3, faction = {"Bandits"} },	
	["Base.BellyButton_DangleGold"] = { price = 20, faction = {"Bandits"} },	
	["Base.BellyButton_DangleGoldRuby"] = { price = 20, faction = {"Bandits"} },	
	["Base.BellyButton_DangleSilver"] = { price = 1, faction = {"Bandits"} },	
	["Base.BellyButton_DangleSilverDiamond"] = { price = 1, faction = {"Bandits"} },	
	["Base.BellyButton_RingGold"] = { price = 20, faction = {"Bandits"} },	
	["Base.BellyButton_RingGoldDiamond"] = { price = 2, faction = {"Bandits"} },	
	["Base.BellyButton_RingGoldRuby"] = { price = 2, faction = {"Bandits"} },	
	["Base.BellyButton_RingSilver"] = { price = 1, faction = {"Bandits"} },	
	["Base.BellyButton_RingSilverAmethyst"] = { price = 2, faction = {"Bandits"} },	
	["Base.BellyButton_RingSilverDiamond"] = { price = 2, faction = {"Bandits"} },	
	["Base.BellyButton_RingSilverRuby"] = { price = 2, faction = {"Bandits"} },	
	["Base.BellyButton_StudGold"] = { price = 20, faction = {"Bandits"} },	
	["Base.BellyButton_StudGoldDiamond"] = { price = 20, faction = {"Bandits"} },	
	["Base.BellyButton_StudSilver"] = { price = 2, faction = {"Bandits"} },	
	["Base.BellyButton_StudSilverDiamond"] = { price = 2, faction = {"Bandits"} },	
	["Base.BeerBottle"] = { price = 30, faction = {"Bandits"} },	
	["Base.BeerCan"] = { price = 30, faction = {"Bandits"} },	
	["Greenfire.FreshUnCanna"] = { price = 9, faction = {"Bandits"} },	
	["Base.PillsSleepingTablets"] = { price = 30, faction = {"Bandits"} },	
	--ECO
	["LabItems.CmpFlaskWithLeukocytes"] = { price = 100, faction = {"Ecologists"} },
	["LabItems.CmpFlaskWithAmmoniumSulfate"] = { price = 100, faction = {"Ecologists"} },
	["iMeds.PlasmaBagON"] = { price = 250, faction = {"Ecologists"} },
	["LabItems.MatTaintedBlood"] = { price = 40, faction = {"Ecologists"} },
	["LabItems.MatInfectedBlood"] = { price = 150, faction = {"Ecologists"} },
	["LabItems.LabSyringe"] = { price = 120, faction = {"Ecologists"} },
	["Base.CarBattery1"] = { price = 9, faction = {"Ecologists"} },
	["Base.CarBattery2"] = { price = 100, faction = {"Ecologists"} },
	["Base.CarBattery3"] = { price = 120, faction = {"Ecologists"} },
	["Base.DuctTape"] = { price = 90, faction = {"Ecologists"} },
	["Base.Battery"] = { price = 70, faction = {"Ecologists"} },
	["Base.Flashlight"] = { price = 100, faction = {"Ecologists"} },
	["Base.ElectronicsScrap"] = { price = 15, faction = {"Ecologists"} },
	["Base.Sheet"] = { price = 10, faction = {"Ecologists"} },
	["Base.CampingTentKit"] = { price = 600, faction = {"Ecologists"} },
	["Base.SheetMetal"] = { price = 200, faction = {"Ecologists"} },
	--BANDITS--MILITARY
	["ZBR.Martini"] = { price = 100, faction = {"Bandits", "Military"} },
	["ZBR.LIIT"] = { price = 120, faction = {"Bandits", "Military"} },
	["ZBR.KYCoffee"] = { price = 95, faction = {"Bandits", "Military"} },
	["ZBR.InsaneBloodyMary"] = { price = 150, faction = {"Bandits", "Military"} },
	["ZBR.ImprovedBloodyMary"] = { price = 120, faction = {"Bandits", "Military"} },
	["ZBR.Highball"] = { price = 40, faction = {"Bandits", "Military"} },
	["ZBR.Gin"] = { price = 90, faction = {"Bandits", "Military"} },
	["ZBR.Flip"] = { price = 110, faction = {"Bandits", "Military"} },
	["ZBR.Rum"] = { price = 80, faction = {"Bandits", "Military"} },
	["ZBR.Daiquiri"] = { price = 130, faction = {"Bandits", "Military"} },
	["ZBR.Cocktail"] = { price = 140, faction = {"Bandits", "Military"} },
	["ZBR.Brandy"] = { price = 150, faction = {"Bandits", "Military"} },
	["ZBR.BloodyMary"] = { price = 110, faction = {"Bandits", "Military"} },
	["ZBR.Bitters"] = { price = 55, faction = {"Bandits", "Military"} },
	["ZBR.Moonshine"] = { price = 200, faction = {"Bandits", "Military"} },
	["ZBR.Sidecar"] = { price = 95, faction = {"Bandits", "Military"} },
	["ZBR.Seltzer"] = { price = 55, faction = {"Bandits", "Military"} },
	["ZBR.Tequila"] = { price = 140, faction = {"Bandits", "Military"} },
	["stalkerfood.CossacksVodka"] = { price = 200, faction = {"Bandits", "Military"} },
	["Base.Cigarettes"] = { price = 30, faction = {"Bandits", "Military"} },
	["stalker.ArtifactWrenched"] = { price = 120, faction = {"Ecologists", "Freedom", "Duty"} },
	["stalker.ArtifactUrchin"] = { price = 54, faction = {"Ecologists", "Freedom", "Duty"} },
	["stalker.ArtifactSun"] = { price = 540, faction = {"Ecologists", "Freedom", "Duty"} },
	["stalker.ArtifactStoneFlower"] = { price = 20, faction = {"Ecologists", "Freedom", "Duty"} },
	["stalker.ArtifactSourpuss"] = { price = 90, faction = {"Ecologists", "Freedom", "Duty"} },
	["stalker.ArtifactSoul"] = { price = 150, faction = {"Ecologists", "Freedom", "Duty"} },
	["stalker.ArtifactSnowflake"] = { price = 220, faction = {"Ecologists", "Freedom", "Duty"} },
	["stalker.ArtifactSignet"] = { price = 184, faction = {"Ecologists", "Freedom", "Duty"} },
	["stalker.ArtifactSeraphim"] = { price = 150, faction = {"Ecologists", "Freedom", "Duty"} },
	["stalker.ArtifactPhantomStar"] = { price = 270, faction = {"Ecologists", "Freedom", "Duty"} },
	["stalker.ArtifactPellicle"] = { price = 330, faction = {"Ecologists", "Freedom", "Duty"} },
	["stalker.ArtifactMamasBeads"] = { price = 1000, faction = {"Ecologists", "Freedom", "Duty"} },
	["stalker.ArtifactHeart"] = { price = 650, faction = {"Ecologists", "Freedom", "Duty"} },
	["stalker.ArtifactFountain"] = { price = 450, faction = {"Ecologists", "Freedom", "Duty"} },
	["stalker.ArtifactFirefly"] = { price = 167, faction = {"Ecologists", "Freedom", "Duty"} },
	["stalker.ArtifactEye"] = { price = 200, faction = {"Ecologists", "Freedom", "Duty"} },
	["stalker.ArtifactCrystalThorn"] = { price = 1500, faction = {"Ecologists", "Freedom", "Duty"} },
	["stalker.ArtifactCrystal"] = { price = 2500, faction = {"Ecologists", "Freedom", "Duty"} },
	["stalker.ArtifactChain"] = { price = 205, faction = {"Ecologists", "Freedom", "Duty"} },
	["stalker.ArtifactCell"] = { price = 105, faction = {"Ecologists", "Freedom", "Duty"} },
	--FREEDOM/DUTY/MIL
	["Base.ScrapMetal"] = { price = 20, faction = {"Military", "Freedom", "Duty"} },
	["Base.SmallSheetMetal"] = { price = 70, faction = {"Military", "Freedom", "Duty"} },
	["Base.MetalBar"] = { price = 90, faction = {"Military", "Freedom", "Duty"} },
	["Base.MetalPipe"] = { price = 100, faction = {"Military", "Freedom", "Duty"} },
	["Base.SandBag"] = { price = 40, faction = {"Military", "Freedom", "Duty"} },
	["Base.GravelBag"] = { price = 50, faction = {"Military", "Freedom", "Duty"} },
	["Base.Solvent"] = { price = 150, faction = {"Military", "Freedom", "Duty"} },
	["Greenfire.Cannabis"] = { price = 15, faction = {"Military", "Freedom", "Duty"} },
	["Greenfire.Joint"] = { price = 24, faction = {"Military", "Freedom", "Duty"} },
	["Greenfire.KiefJoint"] = { price = 40, faction = {"Military", "Freedom", "Duty"} },
	--ALLfaction
	["Base.PetrolCan"] = { price = 250, faction = {"Military", "Freedom", "Duty"} },
	["Base.Log"] = { price = 9, faction = {"Military", "Freedom", "Duty"} },
	["Base.Plank"] = { price = 12, faction = {"Military", "Freedom", "Duty"} },
	["Base.Garbagebag"] = { price = 50, faction = {"Military", "Freedom", "Duty"} },
	["Base.RippedSheets"] = { price = 1, faction = {"Military", "Freedom", "Duty"} },
	["Base.KitchenKnife"] = { price = 50, faction = {"Military", "Freedom", "Duty"} }
	
	}

